const STORAGE_KEY='stickLanesCompositions.v1';
const $=s=>document.querySelector(s);
const U=(fac,name,hp,def,atk,speed,range,rate,cost,gen,special={})=>({fac,name,hp,def,atk,speed,range,rate,cost,gen,special,key:fac+'|'+name});
const F={
Medievais:[
U('Medievais','Camponês',30,10,20,6,1,1.4,50,4),U('Medievais','Espadachim',50,40,50,5,1.2,1.1,100,7),U('Medievais','Escudeiro',70,80,20,3,1,1.5,125,9,{block:.35,tank:true}),U('Medievais','Lanceiro',50,40,50,5,2.2,1.35,115,8),U('Medievais','Arqueiro',40,20,50,5,11,1.15,130,9,{ranged:true}),U('Medievais','Besteiro',40,30,70,4,13,2.3,165,12,{armorPierce:.3,ranged:true}),U('Medievais','Cavaleiro',70,60,70,9,1.5,1.25,225,15,{charge:.6}),U('Medievais','Cavaleiro Pesado',90,90,70,5,1.5,1.55,320,21,{charge:.3,tank:true}),U('Medievais','Mercenário',50,30,80,7,1.2,.8,180,11),U('Medievais','Padre',40,20,30,4,9,1.7,200,15,{heal:{cool:6,pct:.15},support:true}),U('Medievais','Inquisidor',60,50,70,5,1.3,1.15,235,17),U('Medievais','Caçador',50,30,60,7,10,1,155,10,{ranged:true}),U('Medievais','Médico',40,20,10,6,2,2,165,13,{heal:{cool:4,pct:.12},support:true}),U('Medievais','Carrasco',70,40,90,3,1.4,2.2,215,16,{execute:.5}),U('Medievais','Comandante',70,70,70,6,1.3,1,250,18),U('Medievais','Catapulta',50,20,90,1,18,4.5,300,24,{splash:true,siege:1.35,ranged:true}),U('Medievais','Balista',50,30,100,1,20,4,325,25,{armorPierce:.45,siege:1.35,ranged:true}),U('Medievais','Aríete',100,80,10,2,1.3,2.8,285,22,{siege:10,tank:true}),U('Medievais','Nobre',60,50,60,7,1.3,.95,175,12),U('Medievais','Rei',60,60,40,4,1.4,1.3,550,30,{unique:true,aura:.2,support:true})],
Alienígenas:[
U('Alienígenas','Gosma',40,10,30,3,1,1.3,55,4,{split:true}),U('Alienígenas','Massa Pulsante',90,50,40,2,1.2,1.7,170,13,{regen:true,tank:true}),U('Alienígenas','Trípode',50,30,60,9,1.3,1,145,9,{charge:.8}),U('Alienígenas','Olho Flutuante',40,20,60,6,10,1.3,155,10,{ranged:true,flying:true}),U('Alienígenas','Fauce Errante',60,30,80,6,1,1.1,180,12,{execute:.25}),U('Alienígenas','Parasita',30,10,30,8,1,.9,120,8,{lifesteal:.5}),U('Alienígenas','Cuspidor',50,30,60,4,9,1.6,190,14,{acid:true,ranged:true}),U('Alienígenas','Bolha Voadora',30,10,70,7,1,9,105,7,{kamikaze:true,flying:true}),U('Alienígenas','Tentacular',70,50,60,3,4,1.5,215,16,{cc:.18}),U('Alienígenas','Cérebro Gigante',50,20,30,2,8,2,250,19,{cc:.24,support:true}),U('Alienígenas','Casulo',80,60,0,1,0,99,225,18,{summon:true,tank:true}),U('Alienígenas','Devorador',80,50,80,5,1.2,1.4,270,20,{lifesteal:.15}),U('Alienígenas','Translúcido',50,20,70,7,1.3,1,205,15,{dodge:.15}),U('Alienígenas','Aberração Gigante',100,80,100,2,2,2,500,30,{splash:true,tank:true})],
Mentalistas:[
U('Mentalistas','Iniciado',40,20,50,5,8,1.3,110,7,{ranged:true}),U('Mentalistas','Empurrador',50,30,40,4,7,1.6,145,10,{cc:.13}),U('Mentalistas','Puxador',50,30,40,4,8,1.7,165,11,{cc:.16}),U('Mentalistas','Paralisador',40,20,40,4,8,1.7,190,14,{cc:.22}),U('Mentalistas','Confusor',40,20,40,5,9,1.5,175,12,{cc:.25}),U('Mentalistas','Dominador',50,30,30,3,8,2,390,26,{cc:.42,limit:2}),U('Mentalistas','Ilusionista',40,20,40,6,8,1.5,195,14,{dodge:.12,support:true}),U('Mentalistas','Escudeiro Psíquico',70,60,20,3,6,1.8,220,16,{tank:true,support:true}),U('Mentalistas','Levitador',50,30,40,4,8,1.7,220,16,{cc:.24}),U('Mentalistas','Telepata',40,20,70,5,11,1.4,175,12,{armorPierce:.35,ranged:true}),U('Mentalistas','Drenador',60,30,60,5,7,1.3,190,13,{lifesteal:.3}),U('Mentalistas','Oráculo',50,30,50,6,8,1.3,210,15,{dodge:.3,support:true}),U('Mentalistas','Pesadelo',50,30,50,4,8,1.6,240,17,{cc:.2}),U('Mentalistas','Projetor Astral',50,20,60,5,8,1.3,260,19,{support:true}),U('Mentalistas','Mente Coletiva',60,40,10,3,7,2.2,325,23,{groupHeal:{cool:4,pct:.05,targets:3},support:true,limit:2}),U('Mentalistas','Anulador',50,40,40,3,9,1.8,425,28,{cc:.38,limit:1}),U('Mentalistas','Implosor',50,30,80,3,9,2.2,250,18,{splash:true,ranged:true}),U('Mentalistas','Saltador Mental',50,30,70,7,1.2,1,225,16,{dodge:.08}),U('Mentalistas','Mestre Mentalista',70,50,80,5,9,1.2,335,24,{cc:.18,ranged:true}),U('Mentalistas','Entidade Psíquica',80,60,70,3,10,1.5,700,30,{cc:.6,unique:true,ranged:true})]
};
const ALL=Object.values(F).flat(), FAC=Object.keys(F), PAIRS=[['Medievais','Alienígenas'],['Medievais','Mentalistas'],['Alienígenas','Mentalistas']];

function utility(u){let s=u.special,m=1;if(s.block)m+=.12;if(s.armorPierce)m+=s.armorPierce*.32;if(s.charge)m+=s.charge*.13;if(s.splash)m+=.16;if(s.lifesteal)m+=s.lifesteal*.25;if(s.dodge)m+=s.dodge*.28;if(s.cc)m+=s.cc;if(s.heal)m+=.18;if(s.groupHeal)m+=.24;if(s.aura)m+=.18;if(s.regen)m+=.1;if(s.flying)m+=.04;if(s.summon)m+=.12;return m}
function rawPower(u){let dps=u.atk/Math.max(.35,u.rate),ehp=u.hp*(1+u.def/115),r=1+Math.min(20,u.range)*.022,v=1+u.speed*.018;return Math.sqrt(Math.max(1,dps)*Math.max(1,ehp))*r*v*utility(u)}
function value(u){return rawPower(u)/Math.pow(Math.max(30,u.cost),.82)/(1+u.gen*.006)}
function pickWeighted(pool,n){let work=[...pool],out=[];while(out.length<n&&work.length){let weights=work.map(u=>Math.pow(value(u),1.5)*(.55+Math.random()*.9)),sum=weights.reduce((a,b)=>a+b,0),r=Math.random()*sum,i=0;for(;i<weights.length-1;i++){r-=weights[i];if(r<=0)break}out.push(work.splice(i,1)[0])}return out}
function repairComp(units,pool){let out=[...units];const ensure=(pred)=>{if(out.some(pred))return;let candidates=pool.filter(pred).sort((a,b)=>value(b)-value(a));if(!candidates.length)return;let replace=out.map((u,i)=>[value(u),i]).sort((a,b)=>a[0]-b[0])[0][1];if(!out.includes(candidates[0]))out[replace]=candidates[0]};ensure(u=>u.cost<=130);ensure(u=>u.special.ranged);ensure(u=>u.special.tank);ensure(u=>u.special.support||u.special.heal||u.special.groupHeal);return [...new Map(out.map(u=>[u.key,u])).values()].slice(0,8)}
function makeCandidate(pair,greedy=false){let pool=[...F[pair[0]],...F[pair[1]]],units=greedy?[...pool].sort((a,b)=>value(b)-value(a)).slice(0,8):pickWeighted(pool,8);units=repairComp(units,pool);while(units.length<8){let left=pool.filter(u=>!units.includes(u));units.push(pickWeighted(left,1)[0])}return{id:Math.random().toString(36).slice(2),pair,units,score:0,wins:0,games:0,draws:0,baseDiff:0}}
function generateCandidates(n){let out=[],seen=new Set();for(const pair of PAIRS){let c=makeCandidate(pair,true),sig=c.units.map(u=>u.key).sort().join(';');seen.add(sig);out.push(c)}let guard=0;while(out.length<n&&guard++<500){let pair=PAIRS[out.length%PAIRS.length],c=makeCandidate(pair,false),sig=c.units.map(u=>u.key).sort().join(';');if(!seen.has(sig)){seen.add(sig);out.push(c)}}return out.slice(0,n)}

function newSide(comp){return{comp,gold:500,base:3000,towers:[[600,800,1000],[600,800,1000],[600,800,1000]],lanes:[[],[],[]],ready:new Map(),metrics:{}}}
function metric(side,u){return side.metrics[u.key]||(side.metrics[u.key]={spawns:0,damage:0,structure:0,kills:0,deaths:0})}
function cloneUnit(u){return{u,hp:u.hp,maxHp:u.hp}}
function laneStrength(a){return a.reduce((s,x)=>s+rawPower(x.u)*(x.hp/x.maxHp),0)}
function chooseLane(me,foe){let scores=[0,1,2].map(i=>laneStrength(foe.lanes[i])-laneStrength(me.lanes[i])+Math.random()*25);return scores.indexOf(Math.max(...scores))}
function chooseSpawn(side,t){let avail=side.comp.units.filter(u=>side.gold>=u.cost&&t>=(side.ready.get(u.key)||0));if(!avail.length)return null;return avail.sort((a,b)=>{let sa=value(a)*(a.cost<=side.gold*.55?1.1:1)*(.88+Math.random()*.24),sb=value(b)*(b.cost<=side.gold*.55?1.1:1)*(.88+Math.random()*.24);return sb-sa})[0]}
function spawnAI(me,foe,t){let u=chooseSpawn(me,t);if(!u)return;me.gold-=u.cost;me.ready.set(u.key,t+u.gen);let lane=chooseLane(me,foe);me.lanes[lane].push(cloneUnit(u));metric(me,u).spawns++}
function damageAgainst(actor,target,dt){let u=actor.u,def=target.u.def;if(u.special.armorPierce)def*=1-u.special.armorPierce;let d=u.atk/Math.max(.35,u.rate)*dt;d*=1-Math.min(.75,def/(def+120));if(u.special.splash)d*=1.14;if(u.special.charge)d*=1+u.special.charge*.09;if(u.special.cc)d*=1+u.special.cc*.22;if(u.special.execute&&target.hp/target.maxHp<.3)d*=1+u.special.execute;return d}
function healLane(side,lane,dt){for(const a of lane){let s=a.u.special,rate=0;if(s.heal)rate=a.maxHp*s.heal.pct/s.heal.cool;if(s.groupHeal)rate=a.maxHp*s.groupHeal.pct*s.groupHeal.targets/s.groupHeal.cool;if(!rate)continue;let target=[...lane].filter(x=>x.hp<x.maxHp).sort((x,y)=>x.hp/x.maxHp-y.hp/y.maxHp)[0];if(target)target.hp=Math.min(target.maxHp,target.hp+rate*dt)}for(const a of lane)if(a.u.special.regen)a.hp=Math.min(a.maxHp,a.hp+a.maxHp*.015*dt)}
function fightArmies(A,B,sideA,sideB,dt){healLane(sideA,A,dt);healLane(sideB,B,dt);const strike=(src,dst,srcSide,dstSide)=>{if(!dst.length)return;for(const a of [...src]){if(!dst.length)break;let target=dst[Math.floor(Math.random()*Math.min(3,dst.length))],d=damageAgainst(a,target,dt);target.hp-=d;metric(srcSide,a.u).damage+=d;if(a.u.special.lifesteal)a.hp=Math.min(a.maxHp,a.hp+d*a.u.special.lifesteal);if(target.hp<=0){metric(srcSide,a.u).kills++;metric(dstSide,target.u).deaths++;let i=dst.indexOf(target);if(i>=0)dst.splice(i,1)}}};strike(A,B,sideA,sideB);strike(B,A,sideB,sideA)}
function frontTower(side,lane){let arr=side.towers[lane];for(let i=0;i<arr.length;i++)if(arr[i]>0)return i;return-1}
function towerShoot(defender,lane,attackers,dt){let i=frontTower(defender,lane);if(i<0||!attackers.length)return;let specs=[{atk:24,rate:1.6},{atk:30,rate:1.5},{atk:36,rate:1.4}],s=specs[i],target=attackers[0],d=s.atk/s.rate*dt*(1-Math.min(.65,target.u.def/(target.u.def+140)));target.hp-=d;if(target.hp<=0){metric(defender,target.u);attackers.shift()}}
function hitStructure(attacker,defender,lane,dt){let army=attacker.lanes[lane];if(!army.length)return;towerShoot(defender,lane,army,dt);if(!army.length)return;let ti=frontTower(defender,lane);for(const a of [...army]){let d=a.u.atk/Math.max(.35,a.u.rate)*dt*(a.u.special.siege||1);if(ti>=0){defender.towers[lane][ti]-=d;metric(attacker,a.u).structure+=d;if(defender.towers[lane][ti]<=0){defender.towers[lane][ti]=0;break}}else{defender.base-=d;metric(attacker,a.u).structure+=d;if(defender.base<=0){defender.base=0;break}}}}
function simMatch(c1,c2){let A=newSide(c1),B=newSide(c2),dt=2,maxT=300;for(let t=0;t<=maxT&&A.base>0&&B.base>0;t+=dt){A.gold+=30;B.gold+=30;spawnAI(A,B,t);spawnAI(B,A,t);for(let lane=0;lane<3;lane++){let a=A.lanes[lane],b=B.lanes[lane];if(a.length&&b.length)fightArmies(a,b,A,B,dt);if(a.length&&!b.length)hitStructure(A,B,lane,dt);else if(b.length&&!a.length)hitStructure(B,A,lane,dt)}}let scoreA=A.base-B.base;for(let i=0;i<3;i++){scoreA+=(A.towers[i].reduce((x,y)=>x+y,0)-B.towers[i].reduce((x,y)=>x+y,0))*.35;scoreA+=(laneStrength(A.lanes[i])-laneStrength(B.lanes[i]))*.3}let winner=Math.abs(scoreA)<35?0:(scoreA>0?1:-1);return{winner,A,B,scoreA}}

function mergeMetrics(global,side,won){for(const u of side.comp.units){let g=global[u.key]||(global[u.key]={u,appear:0,wins:0,spawns:0,damage:0,structure:0,kills:0,deaths:0});g.appear++;if(won)g.wins++;let m=side.metrics[u.key];if(m){g.spawns+=m.spawns;g.damage+=m.damage;g.structure+=m.structure;g.kills+=m.kills;g.deaths+=m.deaths}}}
function updateComp(c,result,side){c.games++;if(result.winner===side)c.wins++;else if(result.winner===0)c.draws++;c.baseDiff+=side===1?result.scoreA:-result.scoreA;c.score=(c.wins+c.draws*.5)/c.games+c.baseDiff/c.games/12000}
function pct(n){return (n*100).toFixed(1)+'%'}
function esc(s){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function saveComp(c){let list=[];try{list=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]')}catch{}let name='LAB '+c.pair.join('+')+' '+new Date().toLocaleTimeString().slice(0,5),entry={id:String(Date.now()),name,f1:c.pair[0],f2:c.pair[1],keys:c.units.map(u=>u.key),savedAt:Date.now()};list.push(entry);localStorage.setItem(STORAGE_KEY,JSON.stringify(list.slice(-50)));alert('Composição salva. Ela vai aparecer no jogo normal neste aparelho.')}
window.saveLabComp=i=>saveComp(window.__labComps[i]);

async function run(){let total=Number($('#matchCount').value),n=Number($('#candidateCount').value),cands=generateCandidates(n),stats={},status=$('#labStatus'),bar=$('#progressBar');$('#runLab').disabled=true;$('#bestComps').innerHTML='';$('#unitTable').textContent='Simulando...';$('#diagnostics').textContent='Analisando...';
  let prelim=Math.floor(total*.75),done=0;
  for(let m=0;m<prelim;m++){let i=Math.floor(Math.random()*cands.length),j=Math.floor(Math.random()*(cands.length-1));if(j>=i)j++;let c1=cands[i],c2=cands[j],r=simMatch(c1,c2);updateComp(c1,r,1);updateComp(c2,r,-1);mergeMetrics(stats,r.A,r.winner===1);mergeMetrics(stats,r.B,r.winner===-1);done++;if(m%15===0){bar.style.width=pct(done/total);status.textContent=`Qualificatória: ${done}/${total} partidas virtuais a 10×`;await new Promise(requestAnimationFrame)}}
  let finalists=[...cands].sort((a,b)=>b.score-a.score).slice(0,Math.min(6,cands.length)),remain=total-prelim;
  for(let m=0;m<remain;m++){let i=Math.floor(Math.random()*finalists.length),j=Math.floor(Math.random()*(finalists.length-1));if(j>=i)j++;let c1=finalists[i],c2=finalists[j],r=simMatch(c1,c2);updateComp(c1,r,1);updateComp(c2,r,-1);mergeMetrics(stats,r.A,r.winner===1);mergeMetrics(stats,r.B,r.winner===-1);done++;if(m%12===0){bar.style.width=pct(done/total);status.textContent=`Finais: ${done}/${total} partidas virtuais a 10×`;await new Promise(requestAnimationFrame)}}
  bar.style.width='100%';status.textContent=`Concluído: ${total} partidas. Resultados são heurísticos e servem para apontar suspeitos de balanceamento.`;render(cands,stats);$('#runLab').disabled=false;
}
function render(cands,stats){let ranked=[...cands].filter(c=>c.games).sort((a,b)=>b.score-a.score),top=ranked.slice(0,8);window.__labComps=top;$('#bestComps').innerHTML=top.map((c,i)=>`<div class="compCard"><strong>#${i+1} ${esc(c.pair.join(' + '))}</strong> <span class="badge">${pct((c.wins+c.draws*.5)/c.games)}</span><div class="compUnits">${c.units.map(u=>esc(u.name)).join(' • ')}</div><button class="secondary" onclick="saveLabComp(${i})">Salvar no jogo</button></div>`).join('');
let arr=Object.values(stats).filter(x=>x.appear>=4).map(x=>({...x,wr:(x.wins/x.appear),dmgPerSpawn:x.damage/Math.max(1,x.spawns),structPerSpawn:x.structure/Math.max(1,x.spawns)})).sort((a,b)=>b.wr-a.wr);let op=arr.filter(x=>x.appear>=8&&x.wr>=.60).slice(0,5),weak=[...arr].reverse().filter(x=>x.appear>=8&&x.wr<=.40).slice(0,5);$('#diagnostics').innerHTML=`<p><strong class="warning">Suspeitos de fortes:</strong> ${op.length?op.map(x=>`${esc(x.u.name)} (${pct(x.wr)})`).join(', '):'nenhum sinal forte ainda'}</p><p><strong class="good">Suspeitos de fracos:</strong> ${weak.length?weak.map(x=>`${esc(x.u.name)} (${pct(x.wr)})`).join(', '):'nenhum sinal forte ainda'}</p><p class="muted">Win rate aqui significa: taxa de vitória das composições que continham a unidade. Não é prova isolada de que ela está quebrada; composição e pareamento influenciam.</p>`;
$('#unitTable').innerHTML=`<table><thead><tr><th>Unidade</th><th>Facção</th><th>Presenças</th><th>Win rate</th><th>Spawns</th><th>Dano/spawn</th><th>Estrutura/spawn</th><th>Leitura</th></tr></thead><tbody>${arr.map(x=>{let label=x.wr>=.60?'forte?':x.wr<=.40?'fraca?':'ok',w=Math.max(0,Math.min(100,x.wr*100));return`<tr><td>${esc(x.u.name)}</td><td>${esc(x.u.fac)}</td><td>${x.appear}</td><td><div class="meter"><i style="width:${w}%"></i></div>${pct(x.wr)}</td><td>${x.spawns}</td><td>${Math.round(x.dmgPerSpawn)}</td><td>${Math.round(x.structPerSpawn)}</td><td>${label}</td></tr>`}).join('')}</tbody></table>`}
$('#runLab').onclick=run;
