const TAGS={
"Camponês":["Corpo a corpo"],"Espadachim":["Corpo a corpo"],"Escudeiro":["Tanque"],"Lanceiro":["Corpo a corpo"],"Arqueiro":["À distância"],"Besteiro":["À distância","Perfurante"],"Cavaleiro":["Elite"],"Cavaleiro Pesado":["Tanque","Elite"],"Mercenário":["Assassino"],"Padre":["Suporte","À distância"],"Inquisidor":["Elite"],"Caçador":["À distância"],"Médico":["Suporte"],"Carrasco":["Elite"],"Comandante":["Elite"],"Catapulta":["Cerco","À distância"],"Balista":["Cerco","À distância"],"Aríete":["Cerco","Tanque"],"Nobre":["Elite"],"Rei":["Única","Suporte"],
"Gosma":["Monstro"],"Massa Pulsante":["Tanque","Monstro"],"Trípode":["Monstro"],"Olho Flutuante":["À distância","Voador"],"Fauce Errante":["Monstro"],"Parasita":["Assassino","Controle"],"Cuspidor":["À distância"],"Bolha Voadora":["Voador","Explosivo"],"Tentacular":["Controle"],"Cérebro Gigante":["Suporte","Controle"],"Casulo":["Invocador"],"Devorador":["Elite","Monstro"],"Translúcido":["Assassino"],"Aberração Gigante":["Tanque","Elite"],
"Iniciado":["À distância"],"Empurrador":["Controle"],"Puxador":["Controle"],"Paralisador":["Controle"],"Confusor":["Controle"],"Dominador":["Controle","Elite"],"Ilusionista":["Suporte","Controle"],"Escudeiro Psíquico":["Tanque","Suporte"],"Levitador":["Controle"],"Telepata":["À distância","Perfurante"],"Drenador":["Corpo a corpo"],"Oráculo":["Suporte"],"Pesadelo":["Controle"],"Projetor Astral":["Suporte","Elite"],"Mente Coletiva":["Suporte"],"Anulador":["Controle","Elite"],"Implosor":["À distância"],"Saltador Mental":["Assassino"],"Mestre Mentalista":["Elite","Controle"],"Entidade Psíquica":["Única","Controle","Elite"]};
function U(name,hp,def,atk,speed,range,rate,cost,gen,special={}){return{name,hp,def,atk,speed,range,rate,cost,gen,special,tags:TAGS[name]||[]}}
const FACTIONS={
Medievais:[U("Camponês",30,10,20,6,1,1.4,50,4),U("Espadachim",50,40,50,5,1.2,1.1,100,7),U("Escudeiro",70,80,20,3,1,1.5,125,9,{block:.35}),U("Lanceiro",50,40,50,5,2.2,1.35,115,8),U("Arqueiro",40,20,50,5,11,1.15,130,9),U("Besteiro",40,30,70,4,13,2.3,165,12,{armorPierce:.3}),U("Cavaleiro",70,60,70,9,1.5,1.25,225,15,{charge:.6}),U("Cavaleiro Pesado",90,90,70,5,1.5,1.55,320,21,{charge:.3}),U("Mercenário",50,30,80,7,1.2,.8,180,11),U("Padre",40,20,30,4,9,1.7,200,15,{heal:{cool:6,pct:.15,range:8}}),U("Inquisidor",60,50,70,5,1.3,1.15,235,17),U("Caçador",50,30,60,7,10,1,155,10),U("Médico",40,20,10,6,2,2,165,13,{heal:{cool:4,pct:.12,range:3}}),U("Carrasco",70,40,90,3,1.4,2.2,215,16,{execute:.5}),U("Comandante",70,70,70,6,1.3,1,250,18),U("Catapulta",50,20,90,1,18,4.5,300,24,{splash:true}),U("Balista",50,30,100,1,20,4,325,25,{armorPierce:.45}),U("Aríete",100,80,10,2,1.3,2.8,285,22,{siege:10}),U("Nobre",60,50,60,7,1.3,.95,175,12),U("Rei",60,60,40,4,1.4,1.3,550,30,{unique:true,kingAura:.2})],
Alienígenas:[U("Gosma",40,10,30,3,1,1.3,55,4,{split:true}),U("Massa Pulsante",90,50,40,2,1.2,1.7,170,13,{regen:true}),U("Trípode",50,30,60,9,1.3,1,145,9,{charge:.8}),U("Olho Flutuante",40,20,60,6,10,1.3,155,10,{flying:true}),U("Fauce Errante",60,30,80,6,1,1.1,180,12,{execute:.25}),U("Parasita",30,10,30,8,1,.9,120,8,{lifesteal:.5}),U("Cuspidor",50,30,60,4,9,1.6,190,14,{acid:true}),U("Bolha Voadora",30,10,70,7,1,9,105,7,{kamikaze:true,flying:true}),U("Tentacular",70,50,60,3,4,1.5,215,16,{pull:{cool:11,range:10}}),U("Cérebro Gigante",50,20,30,2,8,2,250,19,{confuse:{cool:14,duration:4}}),U("Casulo",80,60,0,1,0,99,225,18,{hatch:18}),U("Devorador",80,50,80,5,1.2,1.4,270,20,{devour:.15}),U("Translúcido",50,20,70,7,1.3,1,205,15),U("Aberração Gigante",100,80,100,2,2,2,500,30,{splash:true})],
Mentalistas:[U("Iniciado",40,20,50,5,8,1.3,110,7),U("Empurrador",50,30,40,4,7,1.6,145,10,{push:{cool:8}}),U("Puxador",50,30,40,4,8,1.7,165,11,{pull:{cool:10,range:10}}),U("Paralisador",40,20,40,4,8,1.7,190,14,{stun:{cool:10,duration:2.5}}),U("Confusor",40,20,40,5,9,1.5,175,12,{confuse:{cool:12,duration:5}}),U("Dominador",50,30,30,3,8,2,390,26,{limit:2,dominate:{cool:30,duration:10,range:10}}),U("Ilusionista",40,20,40,6,8,1.5,195,14),U("Escudeiro Psíquico",70,60,20,3,6,1.8,220,16),U("Levitador",50,30,40,4,8,1.7,220,16,{stun:{cool:14,duration:3}}),U("Telepata",40,20,70,5,11,1.4,175,12,{armorPierce:.35}),U("Drenador",60,30,60,5,7,1.3,190,13,{lifesteal:.3}),U("Oráculo",50,30,50,6,8,1.3,210,15,{dodge:.3}),U("Pesadelo",50,30,50,4,8,1.6,240,17,{fear:{cool:15}}),U("Projetor Astral",50,20,60,5,8,1.3,260,19),U("Mente Coletiva",60,40,10,3,7,2.2,325,23,{limit:2,groupHeal:{cool:4,pct:.05,targets:3,range:10}}),U("Anulador",50,40,40,3,9,1.8,425,28,{limit:1}),U("Implosor",50,30,80,3,9,2.2,250,18,{splash:true}),U("Saltador Mental",50,30,70,7,1.2,1,225,16),U("Mestre Mentalista",70,50,80,5,9,1.2,335,24),U("Entidade Psíquica",80,60,70,3,10,1.5,700,30,{unique:true,steal:{cool:90,range:12}})]};

const $=s=>document.querySelector(s),setup=$('#setup'),gameUI=$('#gameUI'),f1=$('#f1'),f2=$('#f2'),pool=$('#pool'),count=$('#count'),start=$('#start'),canvas=$('#game'),ctx=canvas.getContext('2d');
Object.keys(FACTIONS).forEach(n=>{f1.add(new Option(n,n));f2.add(new Option(n,n))});f1.value='Medievais';f2.value='Alienígenas';
let chosen=[],loadout=[];
function renderPool(){if(f1.value===f2.value)f2.value=Object.keys(FACTIONS).find(x=>x!==f1.value);chosen=[];pool.innerHTML='';[...FACTIONS[f1.value].map(u=>[f1.value,u]),...FACTIONS[f2.value].map(u=>[f2.value,u])].forEach(([fac,u])=>{let b=document.createElement('button');b.className='unitBtn';b.innerHTML=`<b>${u.name}</b><small>${fac} • ${u.cost} ouro • ${u.gen}s</small>${u.tags.slice(0,3).map(t=>`<span class="tag">${t}</span>`).join('')}`;b.onclick=()=>{const k=fac+'|'+u.name,i=chosen.indexOf(k);if(i>=0){chosen.splice(i,1);b.classList.remove('selected')}else if(chosen.length<8){chosen.push(k);b.classList.add('selected')}count.textContent=chosen.length+'/8';start.classList.toggle('disabled',chosen.length!==8)};pool.appendChild(b)});count.textContent='0/8';start.classList.add('disabled')}
f1.onchange=f2.onchange=renderPool;renderPool();

const laneY=[160,450,740],PX=22,BASE_X={1:80,"-1":1720},towerXs={1:[300,520,740],"-1":[1500,1280,1060]};
const towerTypes=[{label:'Traseira',hp:1000,atk:36,range:11,rate:1.4},{label:'Central',hp:800,atk:30,range:10,rate:1.5},{label:'Avançada',hp:600,atk:24,range:9,rate:1.6}];
let units=[],structures=[],effects=[],gold=500,enemyGold=500,playerBase=3000,enemyBase=3000,selectedLane=1,last=performance.now(),running=false,income=0,enemyFactions=[];
const stance=['advance','advance','advance'],spawnCd={};
function byKey(k){let[fac,n]=k.split('|');return{fac,u:FACTIONS[fac].find(x=>x.name===n)}}
start.onclick=()=>{if(chosen.length!==8)return;loadout=chosen.map(byKey);setup.hidden=true;gameUI.hidden=false;buildUI();reset()};$('#restart').onclick=()=>location.reload();
function buildUI(){let lc=$('#laneControls');lc.innerHTML='';['Lane 1','Lane 2','Lane 3'].forEach((name,i)=>{let d=document.createElement('div');d.className='laneControl';d.innerHTML=`<strong>${name}</strong><div class="laneBtns">${[['base','Base'],['behind','Atrás da torre'],['tower','Na torre'],['ahead','À frente'],['advance','Avançar']].map(([v,l])=>`<button class="secondary ${v==='advance'?'active':''}" data-v="${v}">${l}</button>`).join('')}</div>`;d.querySelectorAll('button').forEach(b=>b.onclick=()=>{stance[i]=b.dataset.v;d.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b))});lc.appendChild(d)});let sb=$('#spawnbar');sb.innerHTML='';loadout.forEach(({u},i)=>{let b=document.createElement('button');b.className='spawn';b.innerHTML=`<b>${u.name}</b><small>${u.cost} • ${u.gen}s</small>`;b.onclick=()=>spawnPlayer(i);sb.appendChild(b)})}
canvas.addEventListener('pointerdown',e=>{let r=canvas.getBoundingClientRect(),y=(e.clientY-r.top)*canvas.height/r.height;selectedLane=laneY.map(v=>Math.abs(v-y)).indexOf(Math.min(...laneY.map(v=>Math.abs(v-y))))});
function reset(){units=[];effects=[];gold=enemyGold=500;playerBase=enemyBase=3000;income=0;makeStructures();enemyFactions=Object.keys(FACTIONS).sort(()=>Math.random()-.5).slice(0,2);running=true;last=performance.now();requestAnimationFrame(loop)}
function makeStructures(){structures=[];for(const side of [1,-1])for(let lane=0;lane<3;lane++)towerXs[side].forEach((x,i)=>{let t=towerTypes[i];structures.push({side,lane,x,y:laneY[lane],kind:'tower',...t,maxHp:t.hp,lastAttack:0,dead:false})})}
function aliveTowers(side,lane){return structures.filter(s=>!s.dead&&s.side===side&&s.lane===lane)}
function baseHp(side){return side===1?playerBase:enemyBase}function damageBase(side,d){if(side===1)playerBase=Math.max(0,playerBase-d);else enemyBase=Math.max(0,enemyBase-d)}
function spawnPlayer(i){let{fac,u}=loadout[i],now=performance.now()/1000,k='p'+i;if(gold<u.cost||now<(spawnCd[k]||0))return;if(u.special.unique&&units.some(x=>!x.dead&&x.side===1&&x.name===u.name))return;if(u.special.limit&&units.filter(x=>!x.dead&&x.side===1&&x.name===u.name).length>=u.special.limit)return;gold-=u.cost;spawnCd[k]=now+u.gen;spawnUnit(1,selectedLane,fac,u)}
function spawnUnit(side,lane,fac,u){units.push({side,lane,fac,name:u.name,cost:u.cost||0,tags:u.tags||[],x:side===1?125:1675,y:laneY[lane],hp:u.hp,maxHp:u.hp,def:u.def,atk:u.atk,speed:u.speed,range:u.range,rate:u.rate,special:u.special,lastAttack:0,lastSkill:-999,stunUntil:0,confuseUntil:0,dominatedUntil:0,origSide:side,dead:false,rewarded:false,chargeReady:true,born:performance.now()/1000,anim:Math.random()*10,powerFlash:0})}
function enemyAI(){if(Math.random()>.014)return;let fac=enemyFactions[Math.floor(Math.random()*enemyFactions.length)],u=FACTIONS[fac][Math.floor(Math.random()*FACTIONS[fac].length)];if(enemyGold<u.cost)return;if(u.special.unique&&units.some(x=>!x.dead&&x.side===-1&&x.name===u.name))return;if(u.special.limit&&units.filter(x=>!x.dead&&x.side===-1&&x.name===u.name).length>=u.special.limit)return;enemyGold-=u.cost;spawnUnit(-1,Math.floor(Math.random()*3),fac,u)}
function loop(now){if(!running)return;let dt=Math.min(.033,(now-last)/1000),t=now/1000;last=now;income+=dt;if(income>=2){let n=Math.floor(income/2);gold+=30*n;enemyGold+=30*n;income-=2*n}enemyAI();update(dt,t);updateTowers(t);draw(t);hud(t);if(playerBase<=0||enemyBase<=0){running=false;setTimeout(()=>alert(playerBase>0?'Vitória!':'Derrota!'),50);return}requestAnimationFrame(loop)}
function reward(v,side){if(v.rewarded)return;v.rewarded=true;let r=Math.floor(v.cost*.1);if(side===1)gold+=r;else enemyGold+=r}
function nearestEnemy(u,range){return units.filter(v=>!v.dead&&v.side!==u.side&&v.lane===u.lane&&Math.abs(v.x-u.x)<=range*PX).sort((a,b)=>Math.abs(a.x-u.x)-Math.abs(b.x-u.x))[0]}
function nextStructure(u){let a=aliveTowers(-u.side,u.lane).filter(s=>u.side===1?s.x>=u.x-10:s.x<=u.x+10);return a.length?a.sort((x,y)=>Math.abs(x.x-u.x)-Math.abs(y.x-u.x))[0]:{kind:'base',side:-u.side,lane:u.lane,x:BASE_X[-u.side],y:u.y}}
function defX(u){let o=stance[u.lane];if(o==='base')return BASE_X[u.side]+u.side*70;let a=aliveTowers(u.side,u.lane);if(!a.length)return BASE_X[u.side]+u.side*70;let r=a.sort((x,y)=>Math.abs(x.x-u.x)-Math.abs(y.x-u.x))[0];if(o==='behind')return r.x-u.side*80;if(o==='ahead')return r.x+u.side*80;return r.x-u.side*20}
function kingBuff(u){return units.some(k=>!k.dead&&k.side===u.side&&k.lane===u.lane&&k.name==='Rei')?1.2:1}
function move(u,x,dt){let d=x-u.x;if(Math.abs(d)<5)return;u.x+=Math.sign(d)*u.speed*12*kingBuff(u)*dt}
function update(dt,t){for(const u of units){if(u.dead)continue;if(u.dominatedUntil&&t>u.dominatedUntil){u.side=u.origSide;u.dominatedUntil=0}if(t<u.stunUntil)continue;support(u,t);let foe=nearestEnemy(u,u.range),s=nextStructure(u),sr=Math.abs(s.x-u.x)<=u.range*PX;if(u.tags.includes('Cerco')&&sr){if(t-u.lastAttack>=u.rate/kingBuff(u)){attackStructure(u,s);u.lastAttack=t}}else if(foe){if(t-u.lastAttack>=u.rate/kingBuff(u)){attack(u,foe,t);u.lastAttack=t}}else if(u.side===-1||stance[u.lane]==='advance'){if(sr){if(t-u.lastAttack>=u.rate/kingBuff(u)){attackStructure(u,s);u.lastAttack=t}}else move(u,s.x,dt)}else move(u,defX(u),dt);if(u.special.regen&&t-u.lastAttack>3)u.hp=Math.min(u.maxHp,u.hp+u.maxHp*.015*dt);if(u.special.hatch&&t-u.born>=u.special.hatch){u.dead=true;spawnUnit(u.side,u.lane,u.fac,U('Abominação Jovem',80,40,70,6,1.2,1.1,0,0))}}units=units.filter(u=>!u.dead&&u.hp>0)}
function attackStructure(a,s){let d=a.atk*kingBuff(a);if(a.special.siege)d*=a.special.siege;else if(a.tags.includes('Cerco'))d*=1.35;if(s.kind==='base')damageBase(s.side,d);else{s.hp-=d;if(s.hp<=0){s.hp=0;s.dead=true}}effects.push({type:'impact',x:s.x,y:s.y,t:performance.now()/1000})}
function attack(a,b,t){if(Math.random()<(b.special.dodge||0))return;let d=a.atk*kingBuff(a);if(a.special.armorPierce)d*=1+a.special.armorPierce;if(a.special.charge&&a.chargeReady){d*=1+a.special.charge;a.chargeReady=false}if(a.special.execute&&b.hp/b.maxHp<.3)d*=1+a.special.execute;if(a.special.kamikaze){d*=1.3;a.dead=true}let def=b.def*kingBuff(b),red=Math.min(.75,def/(def+120));d*=1-red;if(b.special.block)d*=1-b.special.block;b.hp-=d;if(b.hp<=0){b.dead=true;reward(b,a.side)}if(a.special.lifesteal)a.hp=Math.min(a.maxHp,a.hp+d*a.special.lifesteal);if(a.special.acid)b.def=Math.max(0,b.def-3);if(a.special.splash)units.filter(v=>v!==b&&!v.dead&&v.side===b.side&&v.lane===b.lane&&Math.abs(v.x-b.x)<48).forEach(v=>{v.hp-=d*.35;if(v.hp<=0){v.dead=true;reward(v,a.side)}});if(a.special.devour&&b.hp<=0)a.hp=Math.min(a.maxHp,a.hp+a.maxHp*a.special.devour);effects.push({type:'impact',x:b.x,y:b.y,t});if(b.hp<=0&&b.special.split)for(let i=0;i<2;i++){spawnUnit(b.side,b.lane,b.fac,U('Gosminha',12,3,9,4,1,.9,0,0));units.at(-1).x=b.x+(i?14:-14)}}
function updateTowers(t){for(const s of structures){if(s.dead||t-s.lastAttack<s.rate)continue;let v=units.filter(u=>!u.dead&&u.side!==s.side&&u.lane===s.lane&&Math.abs(u.x-s.x)<=s.range*PX).sort((a,b)=>Math.abs(a.x-s.x)-Math.abs(b.x-s.x))[0];if(!v)continue;let red=Math.min(.65,v.def/(v.def+140)),d=s.atk*(1-red);v.hp-=d;if(v.hp<=0){v.dead=true;reward(v,s.side)}s.lastAttack=t;effects.push({type:'shot',x1:s.x,y1:s.y-48,x2:v.x,y2:v.y-10,t,side:s.side})}}
function support(u,t){let s=u.special;if(s.heal&&t-u.lastSkill>=s.heal.cool){let a=units.filter(v=>!v.dead&&v.side===u.side&&v.lane===u.lane&&v!==u&&Math.abs(v.x-u.x)<=s.heal.range*PX&&v.hp<v.maxHp).sort((x,y)=>x.hp/x.maxHp-y.hp/y.maxHp)[0];if(a){a.hp=Math.min(a.maxHp,a.hp+a.maxHp*s.heal.pct);u.lastSkill=t;u.powerFlash=t}}if(s.groupHeal&&t-u.lastSkill>=s.groupHeal.cool){let a=units.filter(v=>!v.dead&&v.side===u.side&&v.lane===u.lane&&Math.abs(v.x-u.x)<=s.groupHeal.range*PX&&v.hp<v.maxHp).sort((x,y)=>x.hp/x.maxHp-y.hp/y.maxHp).slice(0,s.groupHeal.targets);if(a.length){a.forEach(v=>v.hp=Math.min(v.maxHp,v.hp+v.maxHp*s.groupHeal.pct));u.lastSkill=t;u.powerFlash=t}}if(s.stun&&t-u.lastSkill>=s.stun.cool){let v=nearestEnemy(u,u.range);if(v){v.stunUntil=t+s.stun.duration;u.lastSkill=t;u.powerFlash=t}}if(s.confuse&&t-u.lastSkill>=s.confuse.cool){let v=nearestEnemy(u,u.range);if(v){v.confuseUntil=t+s.confuse.duration;u.lastSkill=t;u.powerFlash=t}}if(s.dominate&&t-u.lastSkill>=s.dominate.cool){let v=nearestEnemy(u,s.dominate.range);if(v&&!v.special.unique){v.origSide=v.side;v.side=u.side;v.dominatedUntil=t+s.dominate.duration;u.lastSkill=t;u.powerFlash=t}}if(s.steal&&t-u.lastSkill>=s.steal.cool){let v=nearestEnemy(u,s.steal.range);if(v&&v.name!=='Entidade Psíquica'){v.side=u.side;v.origSide=u.side;v.dominatedUntil=0;u.lastSkill=t;u.powerFlash=t}}if(s.pull&&t-u.lastSkill>=s.pull.cool){let v=nearestEnemy(u,s.pull.range||10);if(v){v.x=u.x+u.side*25;u.lastSkill=t;u.powerFlash=t}}if(s.push&&t-u.lastSkill>=s.push.cool){let v=nearestEnemy(u,8);if(v){v.x+=u.side*55;u.lastSkill=t;u.powerFlash=t}}if(s.fear&&t-u.lastSkill>=s.fear.cool){units.filter(v=>!v.dead&&v.side!==u.side&&v.lane===u.lane&&Math.abs(v.x-u.x)<160).forEach(v=>v.x+=u.side*65);u.lastSkill=t;u.powerFlash=t}}
function hud(t){$('#gold').textContent=Math.floor(gold);$('#playerBase').textContent=Math.ceil(playerBase);$('#enemyBase').textContent=Math.ceil(enemyBase);$('#playerTowers').textContent=structures.filter(s=>!s.dead&&s.side===1).length;$('#enemyTowers').textContent=structures.filter(s=>!s.dead&&s.side===-1).length;document.querySelectorAll('.spawn').forEach((b,i)=>{let u=loadout[i].u,left=Math.max(0,(spawnCd['p'+i]||0)-t);b.disabled=gold<u.cost||left>0;b.querySelector('small').textContent=left?left.toFixed(1)+'s':`${u.cost} • ${u.gen}s`})}
function draw(t){ctx.fillStyle='#cbbf9e';ctx.fillRect(0,0,1800,900);for(let i=0;i<3;i++){ctx.fillStyle=i===selectedLane?'#d8cda9':'#cec39f';ctx.fillRect(35,laneY[i]-105,1730,210);ctx.strokeStyle='#8b8065';ctx.lineWidth=3;ctx.strokeRect(35,laneY[i]-105,1730,210)}drawBases();structures.forEach(drawTower);units.forEach(u=>drawUnit(u,t));drawEffects(t)}
function drawBases(){for(const side of [1,-1]){let x=BASE_X[side],hp=baseHp(side);ctx.fillStyle=side===1?'#27384d':'#542c31';ctx.fillRect(x-42,135,84,630);ctx.fillStyle='#161619';ctx.fillRect(x-30,165,60,570);ctx.fillStyle='#111';ctx.fillRect(x-45,105,90,10);ctx.fillStyle='#48a866';ctx.fillRect(x-45,105,90*hp/3000,10);ctx.fillStyle='#eee';ctx.font='bold 17px system-ui';ctx.textAlign='center';ctx.fillText('BASE',x,95)}}
function drawTower(s){if(s.dead)return;ctx.save();ctx.translate(s.x,s.y);ctx.fillStyle=s.side===1?'#3c506b':'#693840';ctx.strokeStyle='#24242a';ctx.lineWidth=4;ctx.fillRect(-24,-55,48,105);ctx.strokeRect(-24,-55,48,105);ctx.beginPath();ctx.moveTo(-34,-55);ctx.lineTo(0,-82);ctx.lineTo(34,-55);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle='#e4bd63';ctx.beginPath();ctx.arc(0,-48,7,0,Math.PI*2);ctx.fill();ctx.fillStyle='#111';ctx.fillRect(-32,-96,64,7);ctx.fillStyle='#46a864';ctx.fillRect(-32,-96,64*s.hp/s.maxHp,7);ctx.fillStyle='#29282b';ctx.font='12px system-ui';ctx.textAlign='center';ctx.fillText(`${s.label} ${Math.ceil(s.hp)}`,0,72);ctx.restore()}
const MENTAL_COLORS={Iniciado:'#4169e1',Empurrador:'#ff8c26',Puxador:'#a8324a',Paralisador:'#89d7ff',Confusor:'#d94cff',Dominador:'#7027b8',Ilusionista:'#f58eea','Escudeiro Psíquico':'#25c7c7',Levitador:'#ddd0ff',Telepata:'#4b3fb5',Drenador:'#7f182e',Oráculo:'#d9bc68',Pesadelo:'#291347','Projetor Astral':'#5fe9ef','Mente Coletiva':'#2faf70',Anulador:'#6e737a',Implosor:'#f2cb3d','Saltador Mental':'#72e546','Mestre Mentalista':'#57207e','Entidade Psíquica':'#111424'};
function drawUnit(u,t){ctx.save();ctx.translate(u.x,u.y+Math.sin(t*7+u.anim)*2);let big=u.name.includes('Gigante')||u.name==='Rei'||u.name==='Entidade Psíquica';ctx.scale(big?1.28:1.05,big?1.28:1.05);if(u.fac==='Alienígenas')drawAlien(u,t);else if(u.fac==='Mentalistas')drawMental(u,t);else drawMedieval(u,t);ctx.scale(big?1/1.28:1/1.05,big?1/1.28:1/1.05);ctx.fillStyle='#111';ctx.fillRect(-28,-68,56,7);ctx.fillStyle='#35a65d';ctx.fillRect(-28,-68,56*Math.max(0,u.hp/u.maxHp),7);ctx.fillStyle='#17171a';ctx.font='bold 12px system-ui';ctx.textAlign='center';ctx.fillText(u.name,0,65);ctx.restore()}
function drawMedieval(u,t){let c=u.side===1?'#4b78b8':'#b84949';ctx.strokeStyle=c;ctx.fillStyle=c;ctx.lineWidth=5;ctx.lineCap='round';stickBody();let d=u.side;if(u.tags.includes('À distância')){ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(d*13,-2);ctx.lineTo(d*31,-2);ctx.stroke()}else if(u.tags.includes('Tanque')){ctx.lineWidth=3;ctx.beginPath();ctx.arc(-d*15,6,12,0,Math.PI*2);ctx.stroke()}else{ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(d*14,5);ctx.lineTo(d*31,-11);ctx.stroke()}if(u.name==='Rei'){ctx.beginPath();ctx.moveTo(-10,-38);ctx.lineTo(-5,-49);ctx.lineTo(0,-39);ctx.lineTo(5,-49);ctx.lineTo(10,-38);ctx.stroke()}}
function stickBody(){ctx.beginPath();ctx.arc(0,-25,10,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.moveTo(0,-15);ctx.lineTo(0,24);ctx.moveTo(0,-4);ctx.lineTo(-15,9);ctx.moveTo(0,-4);ctx.lineTo(18,5);ctx.moveTo(0,24);ctx.lineTo(-12,43);ctx.moveTo(0,24);ctx.lineTo(12,43);ctx.stroke()}
function drawAlien(u,t){let enemy=u.side===-1,c=enemy?'#b44c4c':'#45a867';ctx.strokeStyle=c;ctx.fillStyle=c;ctx.lineWidth=4;ctx.lineCap='round';if(u.name==='Gosma'){let g=ctx.createRadialGradient(-6,-5,3,0,5,24);g.addColorStop(0,'#ffe9a3');g.addColorStop(.45,'#d6a52d');g.addColorStop(1,'#8b6410');ctx.fillStyle=g;ctx.beginPath();ctx.ellipse(0,10,24+Math.sin(t*6)*2,18,0,0,Math.PI*2);ctx.fill();if(t-u.lastAttack<.22){ctx.strokeStyle='#c99724';ctx.lineWidth=8;ctx.beginPath();ctx.moveTo(12,4);ctx.quadraticCurveTo(30,-2,40,5);ctx.stroke()}}else if(u.name==='Massa Pulsante'){let p=1+Math.sin(t*4)*.08;ctx.scale(p,p);ctx.fillStyle=enemy?'#7d3138':'#6b3f78';ctx.beginPath();ctx.ellipse(0,5,29,25,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#d384c2';ctx.lineWidth=3;for(let a=0;a<5;a++){ctx.beginPath();ctx.arc(Math.cos(a)*13,Math.sin(a)*10,4+Math.sin(t*5+a)*2,0,Math.PI*2);ctx.stroke()}}else if(u.name==='Trípode'){ctx.fillStyle=c;ctx.beginPath();ctx.ellipse(0,-15,16,12,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle=c;ctx.lineWidth=5;[-12,0,12].forEach((x,i)=>{ctx.beginPath();ctx.moveTo(x,-7);ctx.lineTo(x+(i-1)*9,40);ctx.stroke()})}else if(u.name==='Olho Flutuante'){ctx.fillStyle=enemy?'#a35a5a':'#6f9a72';ctx.beginPath();ctx.ellipse(0,-5,22,17,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#efe6c5';ctx.beginPath();ctx.arc(0,-5,10,0,Math.PI*2);ctx.fill();ctx.fillStyle='#18181b';ctx.beginPath();ctx.arc(2,-5,4,0,Math.PI*2);ctx.fill()}else if(u.name==='Fauce Errante'){ctx.fillStyle=c;ctx.beginPath();ctx.ellipse(0,8,27,20,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#17171a';ctx.beginPath();ctx.ellipse(5,8,20,10,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#eee1bf';for(let x=-10;x<=18;x+=7){ctx.beginPath();ctx.moveTo(x,1);ctx.lineTo(x+3,7);ctx.lineTo(x+6,1);ctx.fill()}ctx.strokeStyle=c;ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(-15,22);ctx.lineTo(-20,42);ctx.moveTo(15,22);ctx.lineTo(20,42);ctx.stroke()}else if(u.name==='Parasita'){ctx.strokeStyle=c;ctx.lineWidth=8;ctx.beginPath();ctx.moveTo(-18,22);ctx.quadraticCurveTo(-5,-3,10,10);ctx.stroke();ctx.fillStyle=c;ctx.beginPath();ctx.arc(14,8,10,0,Math.PI*2);ctx.fill()}else if(u.name==='Cuspidor'){ctx.fillStyle=c;ctx.fillRect(-22,-20,44,40);ctx.strokeStyle=c;ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(-12,20);ctx.lineTo(-12,38);ctx.lineTo(-26,38);ctx.moveTo(12,20);ctx.lineTo(12,38);ctx.lineTo(26,38);ctx.stroke();ctx.fillStyle='#17171a';ctx.fillRect(u.side*10-5,-6,12,8)}else{ctx.strokeStyle=c;ctx.fillStyle=c;stickBody();if(u.name==='Tentacular'){ctx.beginPath();ctx.moveTo(-12,5);ctx.quadraticCurveTo(-36,-5,-28,-34);ctx.moveTo(12,5);ctx.quadraticCurveTo(36,-5,28,-34);ctx.stroke()}}}
function drawMental(u,t){let base=MENTAL_COLORS[u.name]||'#8a52d1',flash=t-u.powerFlash<.8;ctx.lineWidth=5;ctx.lineCap='round';if(u.name==='Entidade Psíquica'){let grad=ctx.createLinearGradient(-24,-48,24,42),shift=(Math.sin(t*2)+1)/2;grad.addColorStop(0,'#15162b');grad.addColorStop(.25,'#6d2fb3');grad.addColorStop(.5+shift*.12,'#27a67d');grad.addColorStop(.78,'#ef7d2f');grad.addColorStop(1,'#30135e');ctx.strokeStyle=grad;ctx.fillStyle=grad}else{let grad=ctx.createLinearGradient(-18,-40,20,35);grad.addColorStop(0,'#f2f2f2');grad.addColorStop(.18,base);grad.addColorStop(.65,base);grad.addColorStop(1,'#25262a');ctx.strokeStyle=grad;ctx.fillStyle=grad}let wave=flash?Math.sin(t*18)*3:0;ctx.beginPath();ctx.ellipse(0,-25,11+wave*.15,14,0,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.moveTo(0,-11);ctx.lineTo(wave*.2,24);ctx.moveTo(0,-3);ctx.lineTo(-17-wave*.2,10);ctx.moveTo(0,-3);ctx.lineTo(19+wave*.2,7);ctx.moveTo(0,24);ctx.lineTo(-13,44);ctx.moveTo(0,24);ctx.lineTo(13,44);ctx.stroke();ctx.globalAlpha=.35+(flash?.35:0);ctx.strokeStyle=base;ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(0,-7,27+Math.sin(t*4+u.anim)*3,48,0,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1}
function drawEffects(t){for(const e of effects){let age=t-e.t;if(age>.3)continue;ctx.save();ctx.globalAlpha=1-age/.3;if(e.type==='shot'){ctx.strokeStyle=e.side===1?'#f1c95f':'#ff7575';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(e.x1,e.y1);ctx.lineTo(e.x2,e.y2);ctx.stroke()}else{ctx.fillStyle='#fff1a6';ctx.beginPath();ctx.arc(e.x,e.y-15,8+age*28,0,Math.PI*2);ctx.fill()}ctx.restore()}effects=effects.filter(e=>t-e.t<=.3)}
