const TAGS={
"Camponês":["Corpo a corpo"],"Espadachim":["Corpo a corpo"],"Escudeiro":["Tanque"],"Lanceiro":["Corpo a corpo"],"Arqueiro":["À distância"],"Besteiro":["À distância","Perfurante"],"Cavaleiro":["Elite"],"Cavaleiro Pesado":["Tanque","Elite"],"Mercenário":["Assassino"],"Padre":["Suporte","À distância"],"Inquisidor":["Elite"],"Caçador":["À distância"],"Médico":["Suporte"],"Carrasco":["Elite"],"Comandante":["Elite"],"Catapulta":["Cerco","À distância"],"Balista":["Cerco","À distância"],"Aríete":["Cerco","Tanque"],"Nobre":["Elite"],"Rei":["Única","Suporte"],
"Gosma":["Monstro"],"Massa Pulsante":["Tanque","Monstro"],"Trípode":["Monstro"],"Olho Flutuante":["À distância","Voador"],"Fauce Errante":["Monstro"],"Parasita":["Assassino","Controle"],"Cuspidor":["À distância"],"Bolha Voadora":["Voador","Explosivo"],"Tentacular":["Controle"],"Cérebro Gigante":["Suporte","Controle"],"Casulo":["Invocador"],"Devorador":["Elite","Monstro"],"Translúcido":["Assassino"],"Aberração Gigante":["Tanque","Elite"],
"Iniciado":["À distância"],"Empurrador":["Controle"],"Puxador":["Controle"],"Paralisador":["Controle"],"Confusor":["Controle"],"Dominador":["Controle","Elite"],"Ilusionista":["Suporte","Controle"],"Escudeiro Psíquico":["Tanque","Suporte"],"Levitador":["Controle"],"Telepata":["À distância","Perfurante"],"Drenador":["Corpo a corpo"],"Oráculo":["Suporte"],"Pesadelo":["Controle"],"Projetor Astral":["Suporte","Elite"],"Mente Coletiva":["Suporte"],"Anulador":["Controle","Elite"],"Implosor":["À distância"],"Saltador Mental":["Assassino"],"Mestre Mentalista":["Elite","Controle"],"Entidade Psíquica":["Única","Controle","Elite"]};
function U(name,hp,def,atk,speed,range,rate,cost,gen,special={}){return{name,hp,def,atk,speed,range,rate,cost,gen,special,tags:TAGS[name]||[]}}

const FACTIONS={
Medievais:[U("Camponês",30,10,20,6,1,1.4,50,4),U("Espadachim",50,40,50,5,1.2,1.1,100,7),U("Escudeiro",70,80,20,3,1,1.5,125,9,{block:.35}),U("Lanceiro",50,40,50,5,2.2,1.35,115,8),U("Arqueiro",40,20,50,5,11,1.15,130,9),U("Besteiro",40,30,70,4,13,2.3,165,12,{armorPierce:.3}),U("Cavaleiro",70,60,70,9,1.5,1.25,225,15,{charge:.6}),U("Cavaleiro Pesado",90,90,70,5,1.5,1.55,320,21,{charge:.3}),U("Mercenário",50,30,80,7,1.2,.8,180,11),U("Padre",40,20,30,4,9,1.7,200,15,{heal:{cool:6,pct:.15,range:8}}),U("Inquisidor",60,50,70,5,1.3,1.15,235,17),U("Caçador",50,30,60,7,10,1,155,10),U("Médico",40,20,10,6,2,2,165,13,{heal:{cool:4,pct:.12,range:3}}),U("Carrasco",70,40,90,3,1.4,2.2,215,16,{execute:.5}),U("Comandante",70,70,70,6,1.3,1,250,18),U("Catapulta",50,20,90,1,18,4.5,300,24,{splash:true}),U("Balista",50,30,100,1,20,4,325,25,{armorPierce:.45}),U("Aríete",100,80,10,2,1.3,2.8,285,22,{siege:10}),U("Nobre",60,50,60,7,1.3,.95,175,12),U("Rei",60,60,40,4,1.4,1.3,550,30,{unique:true,kingAura:.2})],
Alienígenas:[U("Gosma",40,10,30,3,1,1.3,55,4,{split:true}),U("Massa Pulsante",90,50,40,2,1.2,1.7,170,13,{regen:true}),U("Trípode",50,30,60,9,1.3,1,145,9,{charge:.8}),U("Olho Flutuante",40,20,60,6,10,1.3,155,10,{flying:true}),U("Fauce Errante",60,30,80,6,1,1.1,180,12,{execute:.25}),U("Parasita",30,10,30,8,1,.9,120,8,{lifesteal:.5}),U("Cuspidor",50,30,60,4,9,1.6,190,14,{acid:true}),U("Bolha Voadora",30,10,70,7,1,9,105,7,{kamikaze:true,flying:true}),U("Tentacular",70,50,60,3,4,1.5,215,16,{pull:{cool:11,range:10}}),U("Cérebro Gigante",50,20,30,2,8,2,250,19,{confuse:{cool:14,duration:4}}),U("Casulo",80,60,0,1,0,99,225,18,{hatch:18}),U("Devorador",80,50,80,5,1.2,1.4,270,20,{devour:.15}),U("Translúcido",50,20,70,7,1.3,1,205,15),U("Aberração Gigante",100,80,100,2,2,2,500,30,{splash:true})],
Mentalistas:[U("Iniciado",40,20,50,5,8,1.3,110,7),U("Empurrador",50,30,40,4,7,1.6,145,10,{push:{cool:8}}),U("Puxador",50,30,40,4,8,1.7,165,11,{pull:{cool:10,range:10}}),U("Paralisador",40,20,40,4,8,1.7,190,14,{stun:{cool:10,duration:2.5}}),U("Confusor",40,20,40,5,9,1.5,175,12,{confuse:{cool:12,duration:5}}),U("Dominador",50,30,30,3,8,2,390,26,{limit:2,dominate:{cool:30,duration:10,range:10}}),U("Ilusionista",40,20,40,6,8,1.5,195,14),U("Escudeiro Psíquico",70,60,20,3,6,1.8,220,16),U("Levitador",50,30,40,4,8,1.7,220,16,{stun:{cool:14,duration:3}}),U("Telepata",40,20,70,5,11,1.4,175,12,{armorPierce:.35}),U("Drenador",60,30,60,5,7,1.3,190,13,{lifesteal:.3}),U("Oráculo",50,30,50,6,8,1.3,210,15,{dodge:.3}),U("Pesadelo",50,30,50,4,8,1.6,240,17,{fear:{cool:15}}),U("Projetor Astral",50,20,60,5,8,1.3,260,19),U("Mente Coletiva",60,40,10,3,7,2.2,325,23,{limit:2,groupHeal:{cool:4,pct:.05,targets:3,range:10}}),U("Anulador",50,40,40,3,9,1.8,425,28,{limit:1}),U("Implosor",50,30,80,3,9,2.2,250,18,{splash:true}),U("Saltador Mental",50,30,70,7,1.2,1,225,16),U("Mestre Mentalista",70,50,80,5,9,1.2,335,24),U("Entidade Psíquica",80,60,70,3,10,1.5,700,30,{unique:true,steal:{cool:90,range:12}})]};

const $=s=>document.querySelector(s),setup=$('#setup'),gameUI=$('#gameUI'),f1=$('#f1'),f2=$('#f2'),pool=$('#pool'),count=$('#count'),start=$('#start'),canvas=$('#game'),ctx=canvas.getContext('2d');
Object.keys(FACTIONS).forEach(n=>{f1.add(new Option(n,n));f2.add(new Option(n,n))});f1.value='Medievais';f2.value='Alienígenas';
let chosen=[],loadout=[];
function renderPool(){if(f1.value===f2.value)f2.value=Object.keys(FACTIONS).find(x=>x!==f1.value);chosen=[];pool.innerHTML='';[...FACTIONS[f1.value].map(u=>[f1.value,u]),...FACTIONS[f2.value].map(u=>[f2.value,u])].forEach(([fac,u])=>{let b=document.createElement('button');b.className='unitBtn';b.innerHTML=`<b>${u.name}</b><small>${fac} • ${u.cost} ouro • ${u.gen}s</small>${u.tags.slice(0,3).map(t=>`<span class="tag">${t}</span>`).join('')}`;b.onclick=()=>{const k=fac+'|'+u.name,i=chosen.indexOf(k);if(i>=0){chosen.splice(i,1);b.classList.remove('selected')}else if(chosen.length<8){chosen.push(k);b.classList.add('selected')}count.textContent=chosen.length+'/8';start.classList.toggle('disabled',chosen.length!==8)};pool.appendChild(b)});count.textContent='0/8';start.classList.add('disabled')}
f1.onchange=f2.onchange=renderPool;renderPool();

const VIEW_W=1800,VIEW_H=1000,WORLD_W=9000,BASE_Y=500,PX=25,MOVE_SCALE=24;
const BASE_X={1:180,"-1":8820},LANE_Y=[245,500,755],SPLIT_END=1200,MERGE_START=7800;
const towerXs={1:[1550,2900,4250],"-1":[7450,6100,4750]};
const towerTypes=[{label:'Traseira',hp:1000,atk:36,range:11,rate:1.4},{label:'Central',hp:800,atk:30,range:10,rate:1.5},{label:'Avançada',hp:600,atk:24,range:9,rate:1.6}];
let units=[],structures=[],effects=[],gold=500,enemyGold=500,playerBase=3000,enemyBase=3000,selectedLane=1,last=performance.now(),running=false,income=0,enemyFactions=[],cameraX=0;
const stance=['advance','advance','advance'],spawnCd={};

const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const lerp=(a,b,t)=>a+(b-a)*t;
const smooth=t=>t*t*(3-2*t);
function laneYAt(lane,x){
  if(x<SPLIT_END){let t=clamp((x-BASE_X[1])/(SPLIT_END-BASE_X[1]),0,1);return lerp(BASE_Y,LANE_Y[lane],smooth(t))}
  if(x>MERGE_START){let t=clamp((x-MERGE_START)/(BASE_X[-1]-MERGE_START),0,1);return lerp(LANE_Y[lane],BASE_Y,smooth(t))}
  return LANE_Y[lane];
}
function convergenceZone(x){if(x<SPLIT_END+120)return 1;if(x>MERGE_START-120)return-1;return 0}
function laneCompatible(a,b){if(a.lane===b.lane)return true;let za=convergenceZone(a.x),zb=convergenceZone(b.x);return za!==0&&za===zb}
function yOf(u){return laneYAt(u.lane,u.x)}
function dist(a,b){let dx=a.x-b.x,dy=yOf(a)-yOf(b);return Math.hypot(dx,dy)}

function byKey(k){let[fac,n]=k.split('|');return{fac,u:FACTIONS[fac].find(x=>x.name===n)}}
start.onclick=()=>{if(chosen.length!==8)return;loadout=chosen.map(byKey);setup.hidden=true;gameUI.hidden=false;buildUI();reset()};
$('#restart').onclick=()=>location.reload();
function buildUI(){let lc=$('#laneControls');lc.innerHTML='';['Lane superior','Lane central','Lane inferior'].forEach((name,i)=>{let d=document.createElement('div');d.className='laneControl';d.innerHTML=`<strong>${name}</strong><div class="laneBtns">${[['base','Base'],['behind','Atrás da torre'],['tower','Na torre'],['ahead','À frente'],['advance','Avançar']].map(([v,l])=>`<button class="secondary ${v==='advance'?'active':''}" data-v="${v}">${l}</button>`).join('')}</div>`;d.querySelectorAll('button').forEach(b=>b.onclick=()=>{stance[i]=b.dataset.v;d.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b))});lc.appendChild(d)});let sb=$('#spawnbar');sb.innerHTML='';loadout.forEach(({u},i)=>{let b=document.createElement('button');b.className='spawn';b.innerHTML=`<b>${u.name}</b><small>${u.cost} • ${u.gen}s</small>`;b.onclick=()=>spawnPlayer(i);sb.appendChild(b)})}

function setCamera(v){cameraX=clamp(v,0,WORLD_W-VIEW_W)}
$('#camLeft').onclick=()=>setCamera(cameraX-900);$('#camRight').onclick=()=>setCamera(cameraX+900);$('#camHome').onclick=()=>setCamera(0);$('#camMid').onclick=()=>setCamera((WORLD_W-VIEW_W)/2);$('#camEnemy').onclick=()=>setCamera(WORLD_W-VIEW_W);
let drag=null;
canvas.addEventListener('pointerdown',e=>{let r=canvas.getBoundingClientRect();drag={id:e.pointerId,startX:e.clientX,lastX:e.clientX,startY:e.clientY,moved:false,scale:VIEW_W/r.width};canvas.setPointerCapture(e.pointerId)});
canvas.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;let dx=e.clientX-drag.lastX;if(Math.abs(e.clientX-drag.startX)>7)drag.moved=true;setCamera(cameraX-dx*drag.scale);drag.lastX=e.clientX});
canvas.addEventListener('pointerup',e=>{if(!drag||drag.id!==e.pointerId)return;let r=canvas.getBoundingClientRect(),lx=(e.clientX-r.left)*VIEW_W/r.width,ly=(e.clientY-r.top)*VIEW_H/r.height,wx=cameraX+lx;if(!drag.moved){if(ly<78){let miniX=clamp((lx-20)/(VIEW_W-40),0,1)*WORLD_W;setCamera(miniX-VIEW_W/2)}else{let ds=LANE_Y.map((_,i)=>Math.abs(laneYAt(i,wx)-ly));selectedLane=ds.indexOf(Math.min(...ds))}}drag=null});

function reset(){units=[];effects=[];gold=enemyGold=500;playerBase=enemyBase=3000;income=0;setCamera(0);makeStructures();enemyFactions=Object.keys(FACTIONS).sort(()=>Math.random()-.5).slice(0,2);running=true;last=performance.now();requestAnimationFrame(loop)}
function makeStructures(){structures=[];for(const side of [1,-1])for(let lane=0;lane<3;lane++)towerXs[side].forEach((x,i)=>{let t=towerTypes[i];structures.push({side,lane,x,y:laneYAt(lane,x),kind:'tower',...t,maxHp:t.hp,lastAttack:0,dead:false})})}
function aliveTowers(side,lane){return structures.filter(s=>!s.dead&&s.side===side&&s.lane===lane)}
function baseHp(side){return side===1?playerBase:enemyBase}
function damageBase(side,d){if(side===1)playerBase=Math.max(0,playerBase-d);else enemyBase=Math.max(0,enemyBase-d)}
function spawnPlayer(i){let{fac,u}=loadout[i],now=performance.now()/1000,k='p'+i;if(gold<u.cost||now<(spawnCd[k]||0))return;if(u.special.unique&&units.some(x=>!x.dead&&x.side===1&&x.name===u.name))return;if(u.special.limit&&units.filter(x=>!x.dead&&x.side===1&&x.name===u.name).length>=u.special.limit)return;gold-=u.cost;spawnCd[k]=now+u.gen;spawnUnit(1,selectedLane,fac,u)}
function spawnUnit(side,lane,fac,u){units.push({side,lane,fac,name:u.name,cost:u.cost||0,tags:u.tags||[],x:side===1?280:8720,hp:u.hp,maxHp:u.hp,def:u.def,atk:u.atk,speed:u.speed,range:u.range,rate:u.rate,special:u.special,lastAttack:0,lastSkill:-999,stunUntil:0,confuseUntil:0,dominatedUntil:0,origSide:side,dead:false,rewarded:false,chargeReady:true,born:performance.now()/1000,anim:Math.random()*10,powerFlash:-999})}
function enemyAI(){if(Math.random()>.014)return;let fac=enemyFactions[Math.floor(Math.random()*enemyFactions.length)],u=FACTIONS[fac][Math.floor(Math.random()*FACTIONS[fac].length)];if(enemyGold<u.cost)return;if(u.special.unique&&units.some(x=>!x.dead&&x.side===-1&&x.name===u.name))return;if(u.special.limit&&units.filter(x=>!x.dead&&x.side===-1&&x.name===u.name).length>=u.special.limit)return;enemyGold-=u.cost;spawnUnit(-1,Math.floor(Math.random()*3),fac,u)}
function loop(now){if(!running)return;let dt=Math.min(.033,(now-last)/1000),t=now/1000;last=now;income+=dt;if(income>=2){let n=Math.floor(income/2);gold+=30*n;enemyGold+=30*n;income-=2*n}enemyAI();update(dt,t);updateTowers(t);draw(t);hud(t);if(playerBase<=0||enemyBase<=0){running=false;setTimeout(()=>alert(playerBase>0?'Vitória!':'Derrota!'),50);return}requestAnimationFrame(loop)}
function reward(v,side){if(v.rewarded)return;v.rewarded=true;let r=Math.floor(v.cost*.1);if(side===1)gold+=r;else enemyGold+=r}
function nearestEnemy(u,range){return units.filter(v=>!v.dead&&v.side!==u.side&&laneCompatible(u,v)&&dist(u,v)<=range*PX).sort((a,b)=>dist(u,a)-dist(u,b))[0]}
function nextStructure(u){let a=aliveTowers(-u.side,u.lane).filter(s=>u.side===1?s.x>=u.x-10:s.x<=u.x+10);return a.length?a.sort((x,y)=>Math.abs(x.x-u.x)-Math.abs(y.x-u.x))[0]:{kind:'base',side:-u.side,lane:u.lane,x:BASE_X[-u.side],y:BASE_Y}}
function defX(u){let o=stance[u.lane];if(o==='base')return BASE_X[u.side]+u.side*160;let a=aliveTowers(u.side,u.lane);if(!a.length)return BASE_X[u.side]+u.side*160;let r=a.sort((x,y)=>Math.abs(x.x-u.x)-Math.abs(y.x-u.x))[0];if(o==='behind')return r.x-u.side*140;if(o==='ahead')return r.x+u.side*140;return r.x-u.side*35}
function kingBuff(u){return units.some(k=>!k.dead&&k.side===u.side&&laneCompatible(u,k)&&k.name==='Rei'&&dist(u,k)<450)?1.2:1}
function move(u,x,dt){let d=x-u.x;if(Math.abs(d)<6)return;u.x+=Math.sign(d)*u.speed*MOVE_SCALE*kingBuff(u)*dt;u.x=clamp(u.x,BASE_X[1]+70,BASE_X[-1]-70)}
function update(dt,t){for(const u of units){if(u.dead)continue;if(u.dominatedUntil&&t>u.dominatedUntil){u.side=u.origSide;u.dominatedUntil=0}if(t<u.stunUntil)continue;support(u,t);let foe=nearestEnemy(u,u.range),s=nextStructure(u),sy=s.kind==='base'?BASE_Y:laneYAt(s.lane,s.x),sr=Math.hypot(s.x-u.x,sy-yOf(u))<=u.range*PX;if(u.tags.includes('Cerco')&&sr){if(t-u.lastAttack>=u.rate/kingBuff(u)){attackStructure(u,s,t);u.lastAttack=t}}else if(foe){if(t-u.lastAttack>=u.rate/kingBuff(u)){attack(u,foe,t);u.lastAttack=t}}else if(u.side===-1||stance[u.lane]==='advance'){if(sr){if(t-u.lastAttack>=u.rate/kingBuff(u)){attackStructure(u,s,t);u.lastAttack=t}}else move(u,s.x,dt)}else move(u,defX(u),dt);if(u.special.regen&&t-u.lastAttack>3)u.hp=Math.min(u.maxHp,u.hp+u.maxHp*.015*dt);if(u.special.hatch&&t-u.born>=u.special.hatch){u.dead=true;spawnUnit(u.side,u.lane,u.fac,U('Abominação Jovem',80,40,70,6,1.2,1.1,0,0))}}units=units.filter(u=>!u.dead&&u.hp>0)}
function attackStructure(a,s,t){let d=a.atk*kingBuff(a);if(a.special.siege)d*=a.special.siege;else if(a.tags.includes('Cerco'))d*=1.35;if(s.kind==='base')damageBase(s.side,d);else{s.hp-=d;if(s.hp<=0){s.hp=0;s.dead=true}}let y=s.kind==='base'?BASE_Y:laneYAt(s.lane,s.x);effects.push({type:'impact',x:s.x,y,t,color:'#ffd48a'});if(a.range>4)effects.push({type:'beam',x1:a.x,y1:yOf(a)-20,x2:s.x,y2:y-35,t,color:attackColor(a)})}
function attack(a,b,t){if(Math.random()<(b.special.dodge||0))return;let d=a.atk*kingBuff(a);if(a.special.armorPierce)d*=1+a.special.armorPierce;if(a.special.charge&&a.chargeReady){d*=1+a.special.charge;a.chargeReady=false}if(a.special.execute&&b.hp/b.maxHp<.3)d*=1+a.special.execute;if(a.special.kamikaze){d*=1.3;a.dead=true}let def=b.def*kingBuff(b),red=Math.min(.75,def/(def+120));d*=1-red;if(b.special.block)d*=1-b.special.block;b.hp-=d;if(b.hp<=0){b.dead=true;reward(b,a.side)}if(a.special.lifesteal)a.hp=Math.min(a.maxHp,a.hp+d*a.special.lifesteal);if(a.special.acid)b.def=Math.max(0,b.def-3);if(a.special.splash)units.filter(v=>v!==b&&!v.dead&&v.side===b.side&&laneCompatible(b,v)&&dist(b,v)<75).forEach(v=>{v.hp-=d*.35;if(v.hp<=0){v.dead=true;reward(v,a.side)}});if(a.special.devour&&b.hp<=0)a.hp=Math.min(a.maxHp,a.hp+a.maxHp*a.special.devour);effects.push({type:'impact',x:b.x,y:yOf(b),t,color:attackColor(a)});if(a.range>4||a.fac==='Mentalistas'||a.name==='Cuspidor'||a.name==='Olho Flutuante')effects.push({type:'beam',x1:a.x,y1:yOf(a)-20,x2:b.x,y2:yOf(b)-18,t,color:attackColor(a)});if(b.hp<=0&&b.special.split)for(let i=0;i<2;i++){spawnUnit(b.side,b.lane,b.fac,U('Gosminha',12,3,9,4,1,.9,0,0));units.at(-1).x=b.x+(i?18:-18)}}
function updateTowers(t){for(const s of structures){if(s.dead||t-s.lastAttack<s.rate)continue;let sy=laneYAt(s.lane,s.x),v=units.filter(u=>!u.dead&&u.side!==s.side&&(u.lane===s.lane||convergenceZone(s.x)!==0)&&Math.hypot(u.x-s.x,yOf(u)-sy)<=s.range*PX).sort((a,b)=>Math.hypot(a.x-s.x,yOf(a)-sy)-Math.hypot(b.x-s.x,yOf(b)-sy))[0];if(!v)continue;let red=Math.min(.65,v.def/(v.def+140)),d=s.atk*(1-red);v.hp-=d;if(v.hp<=0){v.dead=true;reward(v,s.side)}s.lastAttack=t;effects.push({type:'shot',x1:s.x,y1:sy-48,x2:v.x,y2:yOf(v)-10,t,side:s.side})}}
function support(u,t){let s=u.special;if(s.heal&&t-u.lastSkill>=s.heal.cool){let a=units.filter(v=>!v.dead&&v.side===u.side&&v!==u&&laneCompatible(u,v)&&dist(u,v)<=s.heal.range*PX&&v.hp<v.maxHp).sort((x,y)=>x.hp/x.maxHp-y.hp/y.maxHp)[0];if(a){a.hp=Math.min(a.maxHp,a.hp+a.maxHp*s.heal.pct);u.lastSkill=t;u.powerFlash=t}}if(s.groupHeal&&t-u.lastSkill>=s.groupHeal.cool){let a=units.filter(v=>!v.dead&&v.side===u.side&&laneCompatible(u,v)&&dist(u,v)<=s.groupHeal.range*PX&&v.hp<v.maxHp).sort((x,y)=>x.hp/x.maxHp-y.hp/y.maxHp).slice(0,s.groupHeal.targets);if(a.length){a.forEach(v=>v.hp=Math.min(v.maxHp,v.hp+v.maxHp*s.groupHeal.pct));u.lastSkill=t;u.powerFlash=t}}if(s.stun&&t-u.lastSkill>=s.stun.cool){let v=nearestEnemy(u,u.range);if(v){v.stunUntil=t+s.stun.duration;u.lastSkill=t;u.powerFlash=t}}if(s.confuse&&t-u.lastSkill>=s.confuse.cool){let v=nearestEnemy(u,u.range);if(v){v.confuseUntil=t+s.confuse.duration;u.lastSkill=t;u.powerFlash=t}}if(s.dominate&&t-u.lastSkill>=s.dominate.cool){let v=nearestEnemy(u,s.dominate.range);if(v&&!v.special.unique){v.origSide=v.side;v.side=u.side;v.dominatedUntil=t+s.dominate.duration;u.lastSkill=t;u.powerFlash=t}}if(s.steal&&t-u.lastSkill>=s.steal.cool){let v=nearestEnemy(u,s.steal.range);if(v&&v.name!=='Entidade Psíquica'){v.side=u.side;v.origSide=u.side;v.dominatedUntil=0;u.lastSkill=t;u.powerFlash=t}}if(s.pull&&t-u.lastSkill>=s.pull.cool){let v=nearestEnemy(u,s.pull.range||10);if(v){v.x=u.x+u.side*45;u.lastSkill=t;u.powerFlash=t}}if(s.push&&t-u.lastSkill>=s.push.cool){let v=nearestEnemy(u,8);if(v){v.x+=u.side*95;u.lastSkill=t;u.powerFlash=t}}if(s.fear&&t-u.lastSkill>=s.fear.cool){units.filter(v=>!v.dead&&v.side!==u.side&&laneCompatible(u,v)&&dist(u,v)<220).forEach(v=>v.x+=u.side*110);u.lastSkill=t;u.powerFlash=t}}
function hud(t){$('#gold').textContent=Math.floor(gold);$('#playerBase').textContent=Math.ceil(playerBase);$('#enemyBase').textContent=Math.ceil(enemyBase);$('#playerTowers').textContent=structures.filter(s=>!s.dead&&s.side===1).length;$('#enemyTowers').textContent=structures.filter(s=>!s.dead&&s.side===-1).length;document.querySelectorAll('.spawn').forEach((b,i)=>{let u=loadout[i].u,left=Math.max(0,(spawnCd['p'+i]||0)-t);b.disabled=gold<u.cost||left>0;b.querySelector('small').textContent=left?left.toFixed(1)+'s':`${u.cost} • ${u.gen}s`})}

function attackColor(u){if(u.fac==='Mentalistas')return MENTAL_COLORS[u.name]||'#b26cff';if(u.name==='Gosma')return'#e7b73d';if(u.name==='Cuspidor')return'#8ee84d';if(u.name==='Olho Flutuante')return'#f0da78';return u.side===1?'#8cc8ff':'#ff8c8c'}

function draw(t){let bg=ctx.createLinearGradient(0,0,0,VIEW_H);bg.addColorStop(0,'#343a31');bg.addColorStop(.5,'#292f28');bg.addColorStop(1,'#20251f');ctx.fillStyle=bg;ctx.fillRect(0,0,VIEW_W,VIEW_H);drawGroundTexture();ctx.save();ctx.translate(-cameraX,0);drawRoads();drawBases(t);structures.forEach(s=>{if(s.x>cameraX-200&&s.x<cameraX+VIEW_W+200)drawTower(s)});units.filter(u=>u.x>cameraX-150&&u.x<cameraX+VIEW_W+150).sort((a,b)=>yOf(a)-yOf(b)).forEach(u=>drawUnit(u,t));drawEffects(t);ctx.restore();drawMiniMap()}
function seeded(n){let x=Math.sin(n*12.9898)*43758.5453;return x-Math.floor(x)}
function drawGroundTexture(){ctx.save();for(let i=0;i<80;i++){let x=seeded(i+Math.floor(cameraX/50))*VIEW_W,y=85+seeded(i*7+11)*(VIEW_H-110),r=1+seeded(i*13)*3;ctx.fillStyle=i%3?'rgba(220,210,173,.045)':'rgba(0,0,0,.08)';ctx.beginPath();ctx.ellipse(x,y,r*2,r,0,0,Math.PI*2);ctx.fill()}ctx.restore()}
function pathLane(lane){ctx.beginPath();for(let x=BASE_X[1];x<=BASE_X[-1];x+=90){let y=laneYAt(lane,x);if(x===BASE_X[1])ctx.moveTo(x,y);else ctx.lineTo(x,y)}ctx.lineTo(BASE_X[-1],BASE_Y)}
function drawRoads(){for(let lane=0;lane<3;lane++){ctx.save();ctx.translate(0,15);pathLane(lane);ctx.strokeStyle='rgba(0,0,0,.28)';ctx.lineWidth=190;ctx.lineCap='round';ctx.lineJoin='round';ctx.stroke();ctx.restore();pathLane(lane);ctx.strokeStyle=lane===selectedLane?'#7d7355':'#665f4b';ctx.lineWidth=176;ctx.lineCap='round';ctx.lineJoin='round';ctx.stroke();pathLane(lane);let g=ctx.createLinearGradient(BASE_X[1],0,BASE_X[-1],0);g.addColorStop(0,'#a79269');g.addColorStop(.5,'#8f815f');g.addColorStop(1,'#a18b65');ctx.strokeStyle=g;ctx.lineWidth=150;ctx.stroke();pathLane(lane);ctx.strokeStyle=lane===selectedLane?'rgba(244,218,142,.22)':'rgba(255,255,255,.055)';ctx.lineWidth=7;ctx.setLineDash([24,42]);ctx.stroke();ctx.setLineDash([]);for(let x=Math.max(BASE_X[1]+120,Math.floor((cameraX-100)/220)*220);x<Math.min(BASE_X[-1]-120,cameraX+VIEW_W+100);x+=220){let y=laneYAt(lane,x),j=(seeded(x+lane*17)-.5)*90;ctx.fillStyle='rgba(50,44,32,.22)';ctx.beginPath();ctx.ellipse(x,y+j,10+seeded(x)*10,4+seeded(x+2)*5,.2,0,Math.PI*2);ctx.fill()}}}
function roundRect(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
function drawBases(t){for(const side of [1,-1]){let x=BASE_X[side],y=BASE_Y,hp=baseHp(side),dir=side===1?1:-1;ctx.save();ctx.translate(x,y);ctx.fillStyle='rgba(0,0,0,.32)';ctx.beginPath();ctx.ellipse(0,45,125,34,0,0,Math.PI*2);ctx.fill();let face=side===1?'#34475b':'#5a343b',sideFace=side===1?'#263442':'#40262b',top=side===1?'#637d98':'#93606a';ctx.fillStyle=sideFace;ctx.beginPath();ctx.moveTo(-78,-30);ctx.lineTo(74,-30);ctx.lineTo(96,32);ctx.lineTo(-58,32);ctx.closePath();ctx.fill();ctx.fillStyle=face;ctx.fillRect(-72,-105,144,78);ctx.fillStyle=top;ctx.beginPath();ctx.moveTo(-72,-105);ctx.lineTo(-48,-132);ctx.lineTo(92,-132);ctx.lineTo(72,-105);ctx.closePath();ctx.fill();ctx.fillStyle='#17191e';ctx.fillRect(dir*20-18,-76,36,49);ctx.strokeStyle='rgba(237,211,143,.65)';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(-45,-93);ctx.lineTo(45,-93);ctx.stroke();ctx.fillStyle='#111';ctx.fillRect(-72,-155,144,11);ctx.fillStyle='#43a768';ctx.fillRect(-72,-155,144*hp/3000,11);ctx.fillStyle='#f1ead8';ctx.font='700 17px system-ui';ctx.textAlign='center';ctx.fillText(side===1?'SUA BASE':'BASE INIMIGA',0,-168);ctx.fillStyle='rgba(228,205,138,.75)';for(let i=-2;i<=2;i++)ctx.fillRect(i*24-5,-126,10,16+Math.sin(t*2+i)*2);ctx.restore()}}
function drawTower(s){if(s.dead)return;let x=s.x,y=laneYAt(s.lane,s.x),targetX=BASE_X[-s.side],targetY=BASE_Y,ang=Math.atan2(targetY-y,targetX-x);ctx.save();ctx.translate(x,y);ctx.fillStyle='rgba(0,0,0,.28)';ctx.beginPath();ctx.ellipse(0,42,58,19,0,0,Math.PI*2);ctx.fill();let front=s.side===1?'#425a72':'#75434b',dark=s.side===1?'#2d3d4e':'#4d2c32',light=s.side===1?'#7e98af':'#a46c73';ctx.fillStyle=dark;ctx.beginPath();ctx.moveTo(-34,-15);ctx.lineTo(31,-15);ctx.lineTo(45,38);ctx.lineTo(-22,38);ctx.closePath();ctx.fill();ctx.fillStyle=front;ctx.fillRect(-35,-62,70,49);ctx.fillStyle=light;ctx.beginPath();ctx.moveTo(-35,-62);ctx.lineTo(-17,-81);ctx.lineTo(49,-81);ctx.lineTo(35,-62);ctx.closePath();ctx.fill();ctx.strokeStyle='#1e2025';ctx.lineWidth=4;ctx.strokeRect(-35,-62,70,49);ctx.save();ctx.rotate(ang*.34);ctx.strokeStyle='#25272d';ctx.lineWidth=12;ctx.beginPath();ctx.moveTo(0,-71);ctx.lineTo(54,-71);ctx.stroke();ctx.strokeStyle=light;ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(0,-74);ctx.lineTo(54,-74);ctx.stroke();ctx.restore();ctx.fillStyle='#d9b85f';ctx.beginPath();ctx.arc(0,-63,8,0,Math.PI*2);ctx.fill();ctx.fillStyle='#111';ctx.fillRect(-39,-96,78,8);ctx.fillStyle='#45ad69';ctx.fillRect(-39,-96,78*s.hp/s.maxHp,8);ctx.fillStyle='rgba(15,16,19,.75)';roundRect(-46,50,92,24,7);ctx.fill();ctx.fillStyle='#eee7d7';ctx.font='12px system-ui';ctx.textAlign='center';ctx.fillText(`${s.label} ${Math.ceil(s.hp)}`,0,66);ctx.restore()}
function teamPlate(u){ctx.fillStyle='rgba(0,0,0,.25)';ctx.beginPath();ctx.ellipse(0,41,31,10,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle=u.side===1?'rgba(85,171,255,.75)':'rgba(255,101,101,.75)';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(0,39,28,7,0,0,Math.PI*2);ctx.stroke()}
function depthScale(y){return .9+(y/VIEW_H)*.22}
function drawUnit(u,t){let y=yOf(u),bob=Math.sin(t*7+u.anim)*(u.special.flying?5:2),sc=depthScale(y)*(u.name.includes('Gigante')||u.name==='Rei'||u.name==='Entidade Psíquica'?1.24:1);ctx.save();ctx.translate(u.x,y+bob);ctx.scale(sc,sc);teamPlate(u);if(u.fac==='Alienígenas')drawAlien(u,t);else if(u.fac==='Mentalistas')drawMental(u,t);else drawMedieval(u,t);ctx.fillStyle='rgba(10,11,13,.78)';roundRect(-31,-70,62,8,4);ctx.fill();ctx.fillStyle='#48b36b';roundRect(-31,-70,62*Math.max(0,u.hp/u.maxHp),8,4);ctx.fill();ctx.fillStyle='rgba(12,13,16,.72)';roundRect(-43,54,86,20,6);ctx.fill();ctx.fillStyle='#f0eadb';ctx.font='700 11px system-ui';ctx.textAlign='center';ctx.fillText(u.name,0,68);ctx.restore()}

function medievalPalette(u){return u.side===1?{main:'#517caa',light:'#8eafd0',dark:'#263b54'}:{main:'#a84c50',light:'#d17b79',dark:'#57292e'}}
function limb(x1,y1,x2,y2,p,w=6){ctx.strokeStyle='rgba(15,16,18,.55)';ctx.lineWidth=w+4;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(x1+2,y1+3);ctx.lineTo(x2+2,y2+3);ctx.stroke();ctx.strokeStyle=p.main;ctx.lineWidth=w;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();ctx.strokeStyle=p.light;ctx.lineWidth=Math.max(1,w*.22);ctx.beginPath();ctx.moveTo(x1-1,y1-1);ctx.lineTo(x2-1,y2-1);ctx.stroke()}
function stickFighter(u,p,t){let atk=t-u.lastAttack<.18?1:0;ctx.fillStyle=p.dark;ctx.beginPath();ctx.arc(2,-27,12,0,Math.PI*2);ctx.fill();let hg=ctx.createRadialGradient(-4,-33,2,0,-27,13);hg.addColorStop(0,p.light);hg.addColorStop(.45,p.main);hg.addColorStop(1,p.dark);ctx.fillStyle=hg;ctx.beginPath();ctx.arc(0,-29,11,0,Math.PI*2);ctx.fill();limb(0,-18,0,20,p,8);limb(0,-6,-14,7,p,6);limb(0,-6,18+atk*7,3,p,6);limb(0,20,-11,42,p,7);limb(0,20,13,42,p,7)}
function drawHorse(u,p){ctx.fillStyle=p.dark;ctx.beginPath();ctx.ellipse(0,17,34,17,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=p.main;ctx.beginPath();ctx.ellipse(-3,12,31,15,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=p.main;ctx.beginPath();ctx.moveTo(21,7);ctx.quadraticCurveTo(34,-2,31,-18);ctx.quadraticCurveTo(46,-17,48,-7);ctx.quadraticCurveTo(38,3,29,13);ctx.fill();[-18,-5,12,23].forEach((x,i)=>limb(x,23,x+(i%2?5:-4),46,p,5))}
function drawSiege(u,p){ctx.save();if(u.name==='Catapulta'){ctx.fillStyle='#5a4630';ctx.fillRect(-34,8,65,23);ctx.fillStyle='#2d251c';[-23,22].forEach(x=>{ctx.beginPath();ctx.arc(x,35,12,0,Math.PI*2);ctx.fill()});ctx.strokeStyle='#7d6240';ctx.lineWidth=7;ctx.beginPath();ctx.moveTo(-8,9);ctx.lineTo(8,-36);ctx.lineTo(26,-52);ctx.stroke();ctx.fillStyle='#2d2b29';ctx.beginPath();ctx.arc(29,-54,9,0,Math.PI*2);ctx.fill()}else if(u.name==='Balista'){ctx.fillStyle='#5b4631';ctx.fillRect(-35,13,70,18);ctx.fillStyle='#29231d';[-24,24].forEach(x=>{ctx.beginPath();ctx.arc(x,36,10,0,Math.PI*2);ctx.fill()});ctx.strokeStyle='#8d7149';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(-31,-9);ctx.quadraticCurveTo(0,-38,31,-9);ctx.moveTo(-31,-9);ctx.quadraticCurveTo(0,15,31,-9);ctx.moveTo(-5,-9);ctx.lineTo(43,-9);ctx.stroke()}else{ctx.fillStyle='#514130';ctx.fillRect(-38,5,76,28);ctx.fillStyle='#2b241d';[-25,25].forEach(x=>{ctx.beginPath();ctx.arc(x,38,11,0,Math.PI*2);ctx.fill()});ctx.strokeStyle='#927149';ctx.lineWidth=11;ctx.beginPath();ctx.moveTo(-26,4);ctx.lineTo(35,-4);ctx.stroke();ctx.fillStyle='#d2b36d';ctx.beginPath();ctx.moveTo(34,-11);ctx.lineTo(48,-4);ctx.lineTo(34,4);ctx.closePath();ctx.fill()}ctx.restore()}
function drawMedieval(u,t){let p=medievalPalette(u),d=u.side;if(u.tags.includes('Cerco')){drawSiege(u,p);return}if(u.name==='Cavaleiro'||u.name==='Cavaleiro Pesado'){drawHorse(u,p);ctx.save();ctx.translate(-3,-22);ctx.scale(.8,.8);stickFighter(u,p,t);ctx.restore();if(u.name==='Cavaleiro Pesado'){ctx.fillStyle=p.light;ctx.fillRect(-15,-42,30,8)}return}stickFighter(u,p,t);ctx.strokeStyle='#c7a86a';ctx.fillStyle='#c7a86a';ctx.lineWidth=4;switch(u.name){case'Camponês':ctx.strokeStyle='#9b7b4b';ctx.beginPath();ctx.moveTo(d*16,4);ctx.lineTo(d*31,-13);ctx.moveTo(d*26,-8);ctx.lineTo(d*35,-2);ctx.stroke();ctx.fillStyle='#b59254';ctx.beginPath();ctx.ellipse(0,-40,16,4,0,0,Math.PI*2);ctx.fill();break;case'Espadachim':weaponSword(d);break;case'Escudeiro':drawShield(-d,3,p);break;case'Lanceiro':ctx.beginPath();ctx.moveTo(-d*7,3);ctx.lineTo(d*45,-19);ctx.stroke();break;case'Arqueiro':case'Caçador':drawBow(d,u.name==='Caçador');break;case'Besteiro':drawCrossbow(d);break;case'Mercenário':weaponSword(d,.75);weaponSword(-d,.65);break;case'Padre':ctx.beginPath();ctx.moveTo(d*13,8);ctx.lineTo(d*27,-35);ctx.moveTo(d*20,-23);ctx.lineTo(d*33,-23);ctx.stroke();break;case'Inquisidor':ctx.fillStyle='#3d3032';ctx.beginPath();ctx.moveTo(-13,-38);ctx.lineTo(0,-52);ctx.lineTo(13,-38);ctx.closePath();ctx.fill();weaponSword(d);break;case'Médico':ctx.fillStyle='#e7e0cf';ctx.fillRect(-8,-2,16,16);ctx.fillStyle='#b44949';ctx.fillRect(-2,0,4,12);ctx.fillRect(-6,4,12,4);break;case'Carrasco':ctx.fillStyle='#342c2c';ctx.fillRect(-10,-41,20,17);ctx.strokeStyle='#5a4938';ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(d*12,6);ctx.lineTo(d*30,-24);ctx.stroke();ctx.fillStyle='#7d858a';ctx.fillRect(d>0?25:-40,-33,16,19);break;case'Comandante':ctx.fillStyle='#d7bd6b';ctx.fillRect(-2,-51,4,16);ctx.beginPath();ctx.moveTo(0,-51);ctx.quadraticCurveTo(18,-47,13,-36);ctx.fill();weaponSword(d);break;case'Nobre':ctx.strokeStyle='#d9c174';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(0,-42);ctx.quadraticCurveTo(14,-54,22,-45);ctx.stroke();weaponSword(d,.7);break;case'Rei':ctx.fillStyle='#e0c360';ctx.beginPath();ctx.moveTo(-12,-41);ctx.lineTo(-7,-54);ctx.lineTo(0,-44);ctx.lineTo(7,-55);ctx.lineTo(13,-41);ctx.closePath();ctx.fill();ctx.fillStyle='rgba(120,28,34,.75)';ctx.beginPath();ctx.moveTo(-5,-14);ctx.lineTo(-20,24);ctx.lineTo(0,18);ctx.fill();weaponSword(d,.75);break;default:weaponSword(d)}}
function weaponSword(d,s=1){ctx.strokeStyle='#9da5aa';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(d*14,5);ctx.lineTo(d*(32*s),-14*s);ctx.stroke();ctx.strokeStyle='#c7a86a';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(d*19,-1);ctx.lineTo(d*25,5);ctx.stroke()}
function drawShield(d,y,p){ctx.fillStyle=p.dark;ctx.beginPath();ctx.ellipse(d*15,y,13,16,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle=p.light;ctx.lineWidth=3;ctx.stroke()}
function drawBow(d,hood){ctx.strokeStyle='#8f6d3e';ctx.lineWidth=3;ctx.beginPath();ctx.arc(d*19,-1,13,-1.35,1.35,d<0);ctx.stroke();ctx.beginPath();ctx.moveTo(d*12,-1);ctx.lineTo(d*35,-1);ctx.stroke();if(hood){ctx.fillStyle='rgba(35,44,37,.8)';ctx.beginPath();ctx.arc(0,-30,14,Math.PI,0);ctx.fill()}}
function drawCrossbow(d){ctx.strokeStyle='#765a37';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(d*11,0);ctx.lineTo(d*35,0);ctx.moveTo(d*22,-9);ctx.lineTo(d*22,9);ctx.stroke()}

function alienSideTint(u,friend='#5e9f74',enemy='#a75058'){return u.side===1?friend:enemy}
function alienShadow(){ctx.fillStyle='rgba(0,0,0,.18)';ctx.beginPath();ctx.ellipse(0,35,25,8,0,0,Math.PI*2);ctx.fill()}
function drawAlien(u,t){alienShadow();let enemy=u.side===-1,c=alienSideTint(u),atk=t-u.lastAttack<.22;switch(u.name){
case'Gosma':{let wob=Math.sin(t*6+u.anim),g=ctx.createRadialGradient(-9,-7,2,2,7,30);g.addColorStop(0,'#fff0ac');g.addColorStop(.35,'#e0b63d');g.addColorStop(.72,'#ad7a13');g.addColorStop(1,'#65450b');ctx.fillStyle=g;ctx.beginPath();ctx.moveTo(-27,20);ctx.quadraticCurveTo(-31,-7+wob*3,-10,-15);ctx.quadraticCurveTo(8,-25,27,-6-wob*2);ctx.quadraticCurveTo(36,12,20,26);ctx.quadraticCurveTo(-4,36,-27,20);ctx.fill();ctx.fillStyle='rgba(255,245,190,.25)';ctx.beginPath();ctx.ellipse(-8,-8,8,4,-.4,0,Math.PI*2);ctx.fill();if(atk){ctx.strokeStyle='#d7a62b';ctx.lineWidth=10;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(16,4);ctx.quadraticCurveTo(u.side*34,-7,u.side*48,3);ctx.stroke()}break}
case'Massa Pulsante':{let pulse=1+Math.sin(t*4+u.anim)*.06;ctx.save();ctx.scale(pulse,pulse);let g=ctx.createRadialGradient(-12,-18,3,0,3,38);g.addColorStop(0,'#cc9ac7');g.addColorStop(.35,enemy?'#7c3e50':'#6f536f');g.addColorStop(1,'#332a38');ctx.fillStyle=g;ctx.beginPath();ctx.ellipse(0,3,37,31,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#9a7da3';ctx.lineWidth=4;for(let i=0;i<6;i++){let a=i*Math.PI/3;ctx.beginPath();ctx.arc(Math.cos(a)*19,Math.sin(a)*14+2,5+Math.sin(t*5+i)*2,0,Math.PI*2);ctx.stroke()}ctx.fillStyle='rgba(220,199,220,.16)';ctx.beginPath();ctx.ellipse(-12,-13,14,7,-.5,0,Math.PI*2);ctx.fill();ctx.restore();break}
case'Trípode':{let g=ctx.createLinearGradient(-20,-25,20,15);g.addColorStop(0,'#a8b9a9');g.addColorStop(.25,enemy?'#825158':'#577b68');g.addColorStop(1,'#27352d');ctx.fillStyle=g;ctx.beginPath();ctx.ellipse(0,-18,23,15,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle=c;ctx.lineWidth=7;[-17,0,17].forEach((x,i)=>{ctx.beginPath();ctx.moveTo(x,-7);ctx.lineTo(x+(i-1)*13,43);ctx.stroke()});ctx.fillStyle='#d9cf80';ctx.beginPath();ctx.arc(u.side*15,-21,4,0,Math.PI*2);ctx.fill();break}
case'Olho Flutuante':{let float=Math.sin(t*3+u.anim)*3;ctx.save();ctx.translate(0,-11+float);ctx.fillStyle=enemy?'#8a6267':'#78937e';ctx.beginPath();ctx.ellipse(0,-4,28,21,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#e9dfc0';ctx.beginPath();ctx.ellipse(0,-4,17,13,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#705b32';ctx.beginPath();ctx.arc(u.side*3,-4,7,0,Math.PI*2);ctx.fill();ctx.fillStyle='#151619';ctx.beginPath();ctx.arc(u.side*5,-4,3,0,Math.PI*2);ctx.fill();ctx.fillStyle='rgba(255,255,255,.72)';ctx.beginPath();ctx.arc(u.side*7,-7,2,0,Math.PI*2);ctx.fill();ctx.restore();break}
case'Fauce Errante':{ctx.fillStyle=enemy?'#7f4148':'#6d7447';ctx.beginPath();ctx.ellipse(0,8,34,24,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#171416';ctx.beginPath();ctx.ellipse(u.side*5,6,27,13,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#eee0b8';for(let x=-18;x<=19;x+=8){ctx.beginPath();ctx.moveTo(x,-1);ctx.lineTo(x+4,7);ctx.lineTo(x+8,-1);ctx.fill();ctx.beginPath();ctx.moveTo(x,13);ctx.lineTo(x+4,6);ctx.lineTo(x+8,13);ctx.fill()}ctx.strokeStyle=c;ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(-18,25);ctx.lineTo(-23,45);ctx.moveTo(17,25);ctx.lineTo(24,45);ctx.stroke();break}
case'Parasita':{ctx.strokeStyle=enemy?'#944e55':'#6c9d70';ctx.lineWidth=9;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(-24,31);ctx.quadraticCurveTo(-13,4,5,15);ctx.quadraticCurveTo(14,20,18,6);ctx.stroke();ctx.fillStyle=enemy?'#a75b62':'#7ab27e';ctx.beginPath();ctx.ellipse(21,2,13,11,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#301a1c';ctx.beginPath();ctx.arc(u.side*27,2,3,0,Math.PI*2);ctx.fill();break}
case'Cuspidor':{let g=ctx.createLinearGradient(-25,-26,27,25);g.addColorStop(0,enemy?'#b87878':'#93ad69');g.addColorStop(.45,enemy?'#75474b':'#5f7747');g.addColorStop(1,'#283426');ctx.fillStyle=g;ctx.fillRect(-26,-24,52,45);ctx.strokeStyle='#222820';ctx.lineWidth=4;ctx.strokeRect(-26,-24,52,45);ctx.strokeStyle=alienSideTint(u,'#73924f','#8c5559');ctx.lineWidth=8;ctx.lineCap='square';ctx.beginPath();ctx.moveTo(-13,21);ctx.lineTo(-13,43);ctx.lineTo(-30,43);ctx.moveTo(13,21);ctx.lineTo(13,43);ctx.lineTo(30,43);ctx.stroke();ctx.fillStyle='#182015';ctx.fillRect(u.side>0?10:-22,-7,14,10);ctx.fillStyle='#a6ef56';ctx.beginPath();ctx.arc(u.side*24,-2,4+Math.sin(t*7)*1.5,0,Math.PI*2);ctx.fill();break}
case'Bolha Voadora':{let g=ctx.createRadialGradient(-9,-18,2,0,-6,30);g.addColorStop(0,'rgba(236,255,232,.75)');g.addColorStop(.35,enemy?'rgba(225,118,133,.6)':'rgba(115,223,160,.6)');g.addColorStop(1,'rgba(61,85,73,.3)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(0,-8,28,0,Math.PI*2);ctx.fill();ctx.strokeStyle='rgba(230,255,237,.45)';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#d5d56b';ctx.beginPath();ctx.arc(3,-5,7+Math.sin(t*5)*2,0,Math.PI*2);ctx.fill();break}
case'Tentacular':{ctx.fillStyle=enemy?'#783a61':'#4c6b75';ctx.beginPath();ctx.ellipse(0,-3,24,21,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle=c;ctx.lineWidth=6;ctx.lineCap='round';for(let i=0;i<6;i++){let a=(i/5-.5)*2.1,x=Math.sin(a)*18;ctx.beginPath();ctx.moveTo(x,11);ctx.quadraticCurveTo(x*2.1,25+Math.sin(t*4+i)*8,x*2.5,45);ctx.stroke()}ctx.fillStyle='#c4d0c8';ctx.beginPath();ctx.arc(u.side*10,-7,4,0,Math.PI*2);ctx.fill();break}
case'Cérebro Gigante':{ctx.fillStyle='rgba(87,65,94,.55)';ctx.beginPath();ctx.ellipse(0,0,34,28,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle=enemy?'#b37086':'#b28bbf';ctx.lineWidth=4;for(let i=-2;i<=2;i++){ctx.beginPath();ctx.arc(i*10,-2+(i%2)*5,10,Math.PI*.2,Math.PI*1.8);ctx.stroke()}ctx.strokeStyle='#6a646e';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(-13,24);ctx.lineTo(-17,45);ctx.moveTo(13,24);ctx.lineTo(17,45);ctx.stroke();break}
case'Casulo':{let g=ctx.createLinearGradient(-22,-35,22,35);g.addColorStop(0,'#dbc78a');g.addColorStop(.5,enemy?'#8a575f':'#6a8262');g.addColorStop(1,'#332f2c');ctx.fillStyle=g;ctx.beginPath();ctx.ellipse(0,2,24,36,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle='rgba(236,218,169,.55)';ctx.lineWidth=2;for(let i=-2;i<=2;i++){ctx.beginPath();ctx.moveTo(i*8,-29);ctx.quadraticCurveTo(-i*10,2,i*7,31);ctx.stroke()}break}
case'Devorador':{ctx.fillStyle=enemy?'#7a4549':'#536d4e';ctx.beginPath();ctx.ellipse(-3,11,39,20,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#171717';ctx.beginPath();ctx.ellipse(u.side*20,5,19,11,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ead9ae';for(let i=-2;i<=2;i++){let yy=-3+i*4;ctx.beginPath();ctx.moveTo(u.side*8,yy);ctx.lineTo(u.side*24,yy+3);ctx.lineTo(u.side*8,yy+6);ctx.fill()}ctx.strokeStyle=c;ctx.lineWidth=6;[-20,-2,18].forEach((x,i)=>{ctx.beginPath();ctx.moveTo(x,25);ctx.lineTo(x+(i-1)*5,44);ctx.stroke()});ctx.fillStyle='#3e4d39';for(let i=-2;i<=2;i++){ctx.beginPath();ctx.moveTo(i*11,-7);ctx.lineTo(i*11+4,-20);ctx.lineTo(i*11+9,-7);ctx.fill()}break}
case'Translúcido':{ctx.globalAlpha=.48;let g=ctx.createLinearGradient(-18,-45,20,40);g.addColorStop(0,'#edf9ff');g.addColorStop(.35,enemy?'#d7929c':'#8acbd1');g.addColorStop(1,'#59636c');ctx.strokeStyle=g;ctx.lineWidth=7;ctx.fillStyle='rgba(220,245,245,.2)';ctx.beginPath();ctx.ellipse(0,-28,12,15,0,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.beginPath();ctx.moveTo(0,-14);ctx.lineTo(0,22);ctx.moveTo(0,-3);ctx.lineTo(-17,10);ctx.moveTo(0,-3);ctx.lineTo(19,7);ctx.moveTo(0,22);ctx.lineTo(-13,44);ctx.moveTo(0,22);ctx.lineTo(13,44);ctx.stroke();ctx.globalAlpha=1;break}
case'Aberração Gigante':case'Abominação Jovem':default:{ctx.fillStyle=enemy?'#6f3f50':'#4d665f';ctx.beginPath();ctx.ellipse(-3,-3,30,28,.2,0,Math.PI*2);ctx.fill();ctx.strokeStyle=c;ctx.lineWidth=8;ctx.lineCap='round';[[-16,-2,-36,36],[0,8,-7,47],[15,2,35,40],[20,-10,43,-24],[-20,-12,-39,-30]].forEach(a=>{ctx.beginPath();ctx.moveTo(a[0],a[1]);ctx.lineTo(a[2]+Math.sin(t*4+a[0])*3,a[3]);ctx.stroke()});ctx.fillStyle='#d8cf9a';ctx.beginPath();ctx.arc(u.side*13,-10,5,0,Math.PI*2);ctx.fill();break}}
}

const MENTAL_COLORS={Iniciado:'#3f6fe5',Empurrador:'#f08a2c',Puxador:'#a83b52',Paralisador:'#83d5ef',Confusor:'#d751d8',Dominador:'#712fb7',Ilusionista:'#df86c9','Escudeiro Psíquico':'#35b8bd',Levitador:'#c9bdf1',Telepata:'#4c4aa9',Drenador:'#81243b',Oráculo:'#d1b25b',Pesadelo:'#342052','Projetor Astral':'#62dfe3','Mente Coletiva':'#35a26d',Anulador:'#777c82',Implosor:'#e3bf36','Saltador Mental':'#71d848','Mestre Mentalista':'#5a2b7e','Entidade Psíquica':'#16182a'};
function metalGradient(base){let g=ctx.createLinearGradient(-22,-45,24,42);g.addColorStop(0,'#f1f3f5');g.addColorStop(.12,base);g.addColorStop(.42,'#d8dbe0');g.addColorStop(.52,base);g.addColorStop(.82,'#262b31');g.addColorStop(1,base);return g}
function galaxyGradient(t){let g=ctx.createLinearGradient(-30,-50+Math.sin(t)*8,30,50);g.addColorStop(0,'#0b1023');g.addColorStop(.18,'#682f9f');g.addColorStop(.42,'#2ca679');g.addColorStop(.63,'#ef842f');g.addColorStop(.82,'#7c39a8');g.addColorStop(1,'#10152a');return g}
function mentalBodyPath(wave=0){ctx.beginPath();ctx.ellipse(wave*.12,-30,13+Math.abs(wave)*.05,16,0,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.moveTo(-8+wave*.1,-15);ctx.quadraticCurveTo(-15,4,-8,24);ctx.quadraticCurveTo(0,30,8,24);ctx.quadraticCurveTo(15,4,8+wave*.1,-15);ctx.closePath();ctx.fill();ctx.lineWidth=8;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(-7,-8);ctx.lineTo(-21-wave*.15,14);ctx.moveTo(7,-8);ctx.lineTo(22+wave*.15,10);ctx.moveTo(-5,24);ctx.lineTo(-13,45);ctx.moveTo(5,24);ctx.lineTo(13,45);ctx.stroke()}
function drawMental(u,t){let base=MENTAL_COLORS[u.name]||'#8462bc',active=t-u.powerFlash<.9||t-u.lastAttack<.18,wave=active?Math.sin(t*19+u.anim)*5:0,galaxy=u.name==='Entidade Psíquica';ctx.save();if(active){ctx.shadowColor=galaxy?'#8a55d7':base;ctx.shadowBlur=18}let grad=galaxy?galaxyGradient(t):metalGradient(base);ctx.fillStyle=grad;ctx.strokeStyle=grad;mentalBodyPath(wave);ctx.shadowBlur=0;ctx.strokeStyle='rgba(255,255,255,.42)';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(-4,-34,4,7,-.4,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.moveTo(-6,-12);ctx.quadraticCurveTo(-10,4,-5,19);ctx.stroke();if(galaxy){let pts=[[-6,-34],[5,-26],[-4,-3],[4,8],[-5,20],[7,31]];for(let i=0;i<pts.length;i++){let p=pts[i],tw=.45+.4*Math.sin(t*4+i);ctx.globalAlpha=tw;ctx.fillStyle=i%3===0?'#f5d98b':i%3===1?'#8fe0c1':'#d5a1ff';ctx.beginPath();ctx.arc(p[0]+Math.sin(t+i)*1.5,p[1],1.2+i%2,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;if(active){ctx.strokeStyle='rgba(143,224,193,.5)';ctx.lineWidth=2;for(let k=0;k<3;k++){ctx.beginPath();ctx.ellipse(0,-2,29+k*7+Math.sin(t*11+k)*4,48+k*4,0,0,Math.PI*2);ctx.stroke()}}}else if(active){ctx.strokeStyle=base;ctx.globalAlpha=.42;ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(0,-1,27+Math.sin(t*8)*3,47,0,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1}drawMentalGlyph(u,base,t,active);ctx.restore()}
function drawMentalGlyph(u,c,t,active){if(!active&&u.name!=='Oráculo'&&u.name!=='Anulador')return;ctx.save();ctx.strokeStyle=c;ctx.fillStyle=c;ctx.lineWidth=2;let x=u.side*30,y=0;ctx.translate(x,y);switch(u.name){case'Empurrador':case'Puxador':ctx.beginPath();ctx.moveTo(-7,-7);ctx.lineTo(7,0);ctx.lineTo(-7,7);ctx.stroke();break;case'Paralisador':ctx.strokeRect(-7,-7,14,14);break;case'Confusor':ctx.beginPath();ctx.arc(0,0,8,0,Math.PI*1.7);ctx.stroke();break;case'Dominador':ctx.beginPath();ctx.arc(0,0,9,0,Math.PI*2);ctx.moveTo(-9,0);ctx.lineTo(9,0);ctx.stroke();break;case'Anulador':ctx.beginPath();ctx.arc(0,0,8,0,Math.PI*2);ctx.moveTo(-6,6);ctx.lineTo(6,-6);ctx.stroke();break;case'Oráculo':ctx.beginPath();ctx.moveTo(-8,0);ctx.quadraticCurveTo(0,-8,8,0);ctx.quadraticCurveTo(0,8,-8,0);ctx.stroke();break;case'Implosor':ctx.beginPath();for(let i=0;i<6;i++){let a=i*Math.PI/3;ctx.moveTo(Math.cos(a)*3,Math.sin(a)*3);ctx.lineTo(Math.cos(a)*10,Math.sin(a)*10)}ctx.stroke();break;default:ctx.beginPath();ctx.arc(0,0,5+Math.sin(t*8)*2,0,Math.PI*2);ctx.fill()}ctx.restore()}

function drawEffects(t){for(const e of effects){let age=t-e.t;if(age>.34)continue;ctx.save();ctx.globalAlpha=1-age/.34;if(e.type==='shot'){ctx.strokeStyle=e.side===1?'#ffd466':'#ff7b7b';ctx.lineWidth=6;ctx.shadowColor=ctx.strokeStyle;ctx.shadowBlur=10;ctx.beginPath();ctx.moveTo(e.x1,e.y1);ctx.lineTo(e.x2,e.y2);ctx.stroke()}else if(e.type==='beam'){ctx.strokeStyle=e.color||'#fff';ctx.lineWidth=3;ctx.shadowColor=ctx.strokeStyle;ctx.shadowBlur=12;ctx.beginPath();ctx.moveTo(e.x1,e.y1);ctx.lineTo(e.x2,e.y2);ctx.stroke()}else{ctx.fillStyle=e.color||'#fff0a0';ctx.shadowColor=ctx.fillStyle;ctx.shadowBlur=15;ctx.beginPath();ctx.arc(e.x,e.y-12,7+age*35,0,Math.PI*2);ctx.fill()}ctx.restore()}effects=effects.filter(e=>t-e.t<=.35)}
function drawMiniMap(){let x=20,y=17,w=VIEW_W-40,h=48;ctx.save();ctx.fillStyle='rgba(7,8,10,.72)';roundRect(x,y,w,h,12);ctx.fill();ctx.strokeStyle='rgba(255,255,255,.12)';ctx.stroke();let scale=w/WORLD_W;for(let lane=0;lane<3;lane++){ctx.strokeStyle=lane===selectedLane?'rgba(240,209,126,.8)':'rgba(200,194,171,.35)';ctx.lineWidth=4;ctx.beginPath();for(let wx=BASE_X[1];wx<=BASE_X[-1];wx+=180){let mx=x+wx*scale,my=y+h/2+(laneYAt(lane,wx)-BASE_Y)*.055;if(wx===BASE_X[1])ctx.moveTo(mx,my);else ctx.lineTo(mx,my)}ctx.stroke()}ctx.fillStyle='#6ca5d6';ctx.fillRect(x+BASE_X[1]*scale-3,y+8,6,h-16);ctx.fillStyle='#d16d73';ctx.fillRect(x+BASE_X[-1]*scale-3,y+8,6,h-16);ctx.strokeStyle='#efe3bc';ctx.lineWidth=2;ctx.strokeRect(x+cameraX*scale,y+3,VIEW_W*scale,h-6);ctx.fillStyle='rgba(239,227,188,.7)';ctx.font='11px system-ui';ctx.textAlign='center';ctx.fillText('MAPA 5× — toque no minimapa ou arraste o campo',x+w/2,y+h-7);ctx.restore()}
